swagger: '2.0'
info:
  description: This API will return messages from the Ask Marko Chat Bot
  version: 1.0.0
  title: Ask Marko 
host: qa-marko.aramark.net
basePath: /v1/ask
schemes:
- https
securityDefinitions:
  apikey:
    type: apiKey
    in: header
    name: apikey
    description: This HTTP Header variable will verify security
tags:
- name: Ask
  description: This API will return messages from the Ask Marko Chat Bot
parameters:
  bypassCacheParam:
    in: header
    name: bypass-cache
    type: string
    description: This HTTP Header variable will bypass cache
    enum: ['true','false']
    default: false
  smokeParam:
    in: header
    name: smoke
    type: string
    description: When set to 'true' this HTTP Header variable will route to the Smoke environment.  Only applicable in QA
paths:
  /marko:
    post:
      summary: Return a message from the Ask Marko Chat Bot
      operationId: postAskMarko
      parameters:
        - $ref: "#/parameters/bypassCacheParam"
        - name: body
          in: body
          description: Body of the message sent to the Ask Marko Chat Bot
          required: false
          schema:
            $ref: "#/definitions/body"
      tags:
        - Ask
      responses:
        200:
          description: Response from the Ask Marko Chat Bot
          schema:
            type: object
            properties:
              response:
                type: array
                items:
                  $ref: '#/definitions/response'
        404:
          description: Requested resource does not exist.
        405:
          description: HTTP Verb / Operation not supported
definitions:
  body:
    type: object
    properties:
      email:
        type: string
        description: Email address of the authenticated user making the request
      mode:
        type: string
        description: Type of response from the Ask Marko Chat Bot
      channel:
        type: string
        description: Path to the Chat Bot
      message:
        type: string
        description: Message to ask the Ask Marko Chat Bot
  buttons:
    type: object
    properties:
      title:
        type: string
        description: Name of the button
      payload:
        type: string
        description: Message of the button
  content:
    type: object
    properties:
      type:
        type: string
        description: Filetype of the attachment
      url:
        type: string
        description: URL of the attachment
  quickReplies:
    type: object
    properties:
      text:
        type: string
        description: Message of the Quick Replies
      buttons:
        type: array
        items:
          $ref: "#/definitions/buttons"
  insight:
    type: object
    properties:
      text:
        type: string
        description: Message of the insight
  attachment:
    type: object
    properties:
      content:
        type: array
        items:
          $ref: "#/definitions/content"
      text:
        type: string
        description: Message of the attachment
  outputText:
    type: object
    properties:
      text:
        type: string
        description: Message of the output text
  response:
    type: object
    properties:
      outputText:
        type: array
        items:
          $ref: "#/definitions/outputText"
      attachment:
        type: array
        items:
          $ref: "#/definitions/attachment"
      insight:
        type: array
        items:
          $ref: "#/definitions/insight"
      quickReplies:
        type: array
        items:
          $ref: "#/definitions/quickReplies"