swagger: "2.0"
info:
  description: This API will return data related to different Growth metrics
  version: 1.0.0
  title: Growth
host: qa-marko.aramark.net
basePath: /v1/growth
schemes:
- https

# Tags organize operations into groups for presentation in the Swagger UI.
# Each tag has an optional description, which the Swagger UI will display in 
# the tag group header.
tags:
- name: VOC
  description: Voice of the Consumer Survey Results
paths:
  /voc/results/{org_value}:
    get:
      description: Returns VOC Survey Results for a specific Location
      operationId: getVOCResults
      produces:
      - application/json
      tags:
        - VOC
      parameters:
        - in: path
          name: org_value        
          type: string
          description: Aramark Location code for rollup
          required: true
        - in: query 
          name: start_date        
          type: string
          description: Calendar date for responses. "mm/dd/yyyy"
          required: true
        - in: query 
          name: end_date        
          type: string
          description: Calendar date end date for responses. Will use start_date if not provided. "mm/dd/yyyy"
        - name: survey_type
          in: query
          type: string
          description: Comma separated list of codes to determine which type of survey questions to return. "HLTH" - Health, "PERS" - Personalization, "QUAL" - Quality, "SAT" - Satisfaction, "ALL" - All Types
          required: false
          default: 'ALL'
        - name: survey_group
          in: query
          type: string
          description: Comma separated list of codes to determine which survey group to return. "CATERING" - Catering, "DINING" - Dining, "ALL" - All Groups
          required: false 
          default: 'ALL'
        - name: page
          in: query
          type: string
          description: Page number of data set to return
          default: 1
          required: false
        - name: size
          in: query
          type: string
          description: Number of rows in each page to return.
          default: 50
          required: false
        - name: bypass-cache
          in: header
          type: string
          description: This HTTP Header variable will bypass cache.
          default: false
        - name: apikey
          in: header
          type: string
          description: This HTTP Header variable will verify permissions. 
        - name: smoke
          in: header
          type: string
          description: When set to 'true' this HTTP header variable will route the API call to the Integration testing environment.  Only applicable in QA.
          default: false
      responses:
        200:
          description: Provides the service results for a specific unit of measure
          schema:
            type: object
            properties:
              status:
                type: string
                description: ENUM 'Success', 'Error' or 'Not Found'
                default: Success
                example: "Success"
              count:
                type: string
                description: Number of records returned 
                default: '0'
                example: "1"
              # Reference to a Schema Object described in 'definitions' section
              survey_response:
                type: array
                items:
                  $ref: "#/definitions/survey_response"
        404:
          description: Requested resource does not exist.
        405:
          description: HTTP Verb / Operation not supported
definitions:
  survey_response:
    type: object
    properties:
      profit_center:
        type: string
        description: Aramark Profit Center value
      profit_center_name:
        type: string
        description: Aramark Profit Center Name
      location:
        type: string
        description: Aramark Location value
      location_name:
        type: string
        description: Aramark Location Name
      survey_group:
        type: string
        description: Description of the group the survey
      survey_type:
        type: string
        description: Description of the type of survey question
      measure_value:
        type: string
        description: Value of the survey response
      response_date:
        type: string
        description: Calendar date of the survey response
      country:
        type: string
        description: Coutnry code of the response
