swagger: "2.0"
info:
  description: |
    This API will return Employee information
    
    The base endpoint URL for this API in production is: `https://marko.aramark.net/v1/employee`.

    For testing the API with the "Try" tool on this page or in your app, use either our testing server "qa-marko" or our development server "dev-marko".
  version: 1.0.0
  title: Labor Employee
host: qa-marko.aramark.net
basePath: /v1/labor/employee
schemes:
- https
securityDefinitions:
  apikey:
    type: apiKey
    in: header
    name: apikey
    description: This HTTP Header variable will verify security
parameters:
  bypassCacheParam:
    in: header
    name: bypass-cache
    type: string
    description: This HTTP Header variable will bypass cache
    enum: ['true','false']
    default: 'false'
  smokeParam:
    in: header
    name: smoke
    type: string
    description: When set to 'true' this HTTP Header variable will route to the Integration environment.  Only applicable in QA Server
    enum: ['true','false']
    default: 'false'
  employeeIdParam:
    in: query
    name: employee_id        
    type: string
    description: Unique identifier of the employee
    required: true
  effectiveDateParam:
    in: query
    name: effective_date
    type: string
    description: Calendar date for which the accrual balance is effective "MM/DD/YYYY"
    required: true
tags:
- name: Accruals
  description: Get Employee Scheduled Shifts
- name: Manager
  description: Get Manager information for an Employee

paths:
  /accrual:
    # Operations are identified by an HTTP method.  
    get:
      description: |
        Returns a collection of accrual balance information for an employee
        
        ![This endpoint is in production](/themes/portal/images/statuspngs/statusprod.png)
      operationId: getEmployeeAccrual
      tags:
        - Accruals
      produces:
      - application/json
      parameters:
        - $ref: '#/parameters/employeeIdParam'
        - $ref: '#/parameters/effectiveDateParam'
        - $ref: '#/parameters/bypassCacheParam'
        - $ref: '#/parameters/smokeParam'
      responses:
        200:
          description: Provides the accrual balance data
          schema:
            type: object
            properties:
              status:
                type: string
                description: ENUM 'Success', 'Error' or 'Not Found'
                default: Success
              count:
                type: integer
                description: Number of records being returned
              accrual_balances:
                type: array
                items:
                 $ref: '#/definitions/accrual_balances'
        404:
          description: Requested resource does not exist.
        405:
          description: HTTP Verb / Operation not supported
          
  /manager:
    # Operations are identified by an HTTP method.  
    get:
      description: |
        Returns a collection of data for the manager for an employee
        
        ![This endpoint is in production](/themes/portal/images/statuspngs/statusprod.png)
      operationId: getEmployeeManager
      tags:
        - Manager
      produces:
      - application/json
      parameters:
        - $ref: '#/parameters/employeeIdParam'
        - $ref: '#/parameters/bypassCacheParam'
        - $ref: '#/parameters/smokeParam' 
      responses:
        200:
          description: Provides the Supervisor data for an employee
          schema:
            type: object
            properties:
              status:
                type: string
                description: ENUM 'Success', 'Error' or 'Not Found'
                default: Success
              count:
                type: integer
                description: Number of records being returned
              manager:
                type: array
                items:
                 $ref: '#/definitions/manager'
        404:
          description: Requested resource does not exist.
        405:
          description: HTTP Verb / Operation not supported
# The definitions section contains a set of named Schema Objects.  Each schema
# object describes a reusable data type, which can be reference by name.
definitions:
  accrual_balances:
    type: object
    properties:
      employee_id:
        type: string
        description: Unique ID for the employee
      employee_name:
        type: string
        description: First and Last name of the employee
      accrual_code:
        type: string
        description: Unique code to describe the type of accrual balance
      accrual_balance:
        type: string
        description: Actual amount of the accrual for the employee
  manager:
    type: object
    properties:
      manager_id:
        type: string
        description: Unqiue ID for the employee's manager