swagger: "2.0"
info:
  description: This API will return Labor Forecasting Data
  version: 1.0.0
  title: Labor Forecast
host: qa-marko.aramark.net
basePath: /v1/labor/daily
schemes:
- https
tags:
- name: Labor Daily Forecast
  description: Get Daily Labor Forecast data
paths:
  /forecast/{org_value}:
    # Operations are identified by an HTTP method.  
    get:
      description: Returns Labor Daily Forecast
      operationId: getDailyLaborForecast
      tags:
        - Labor Daily Forecast
      produces:
      - application/json
      parameters:
        - in: path 
          name: org_value        
          type: string
          description: Provide a Business Organization code to filter data set
          required: true
        - in: query 
          name: start_date        
          type: string
          description: Calendar date for daily transactions. "mm/dd/yyyy"
          required: true
        - in: query 
          name: end_date        
          type: string
          description: Calendar date end date for daily transactions. Will use start_date if not provided. "mm/dd/yyyy"
          required: false
        - in: query
          name: sort
          type: string
          description: Value to determine direction of date range sorting
          enum: ['ASC','DESC']
        - name: bypass-cache
          in: header
          type: string
          description: This HTTP Header variable will bypass cache.
          enum: ['true','false']
          default: false
        - name: apikey
          in: header
          type: string
          description: This HTTP Header variable will verify permissions. 
          default: dcF1wtqbCH6bgZ1mVASiGUu6mu8rS8YA
        - name: smoke
          in: header
          type: string
          description: When set to 'true' this HTTP header variable will route the API call to the Integration testing environment.  Only applicable in QA.
          default: false
      responses:
        200:
          description: Provides the labor forecast data
          schema:
            type: object
            properties:
              status:
                type: string
                description: ENUM 'Success', 'Error' or 'Not Found'
                default: Success
              count:
                type: integer
                description: Number of records being returned
                
              labor_forecast:
                type: array
                items:
                 $ref: '#/definitions/labor_forecast'
        404:
          description: Requested resource does not exist.
        405:
          description: HTTP Verb / Operation not supported
# The definitions section contains a set of named Schema Objects.  Each schema
# object describes a reusable data type, which can be reference by name.
definitions:
  labor_forecast:
    type: object
    properties:
      calendar_date:
        type: string
        description: Date of returned data MM/dd/yyy Format
      org_value:
        type: string
        description: Aramark Organization code
      actual_hours:
        type: number
        description: Actual Hours
      actual_revenue:
        type: number
        description: Actual Revenue
      actual_transactions:
        type: number
        description: Actual Transactions.  Only applicable to Location
      actual_wages:
        type: number
        description: Actual Wages
      allocated_hours:
        type: number
        description: Allocated Hours
      allocated_hours_template:
        type: number
        description: Allocated hours Template. Only applicable to Location
      allocated_wages:
        type: number
        description: Allocated Wages
      allocated_wages_template:
        type: number
        description: Allocated Wages Templated. Only applicable to Location
      allowable_hours:
        type: number
        description: Allowable Hours
      allowable_wages:
        type: number
        description: Allowable Wages
      custom_count:
        type: number
        description: Custom Count
      earned_hours:
        type: number
        description: Earned Hours
      earned_wages: 
        type: number
        description: Earned Wages
      labor_cost_pct_adjusted:
        type: number
        description: Labor Cost Percent Adjusted
      labor_cost_pct_proj:
        type: number
        description: Labor Cost Percent Projected
      lst_day_completed_act:
        type: number
        description: Labor Scheduling Tool Completed Actual Count
      lst_day_completed_proj:
        type: number
        description: Labor Scheduling Tool Completed Projected Count
      lst_day_required_act:
        type: number
        description: Labor Scheduling Tool Required Actual Count
      lst_day_required_proj:
        type: number
        description: Labor Scheduling Tool Required Projected Count
      non_kronos_hours:
        type: number
        description: Non Kronos Hours
      non_kronos_wages:
        type: number
        description: Non Kronos Wages
      plan_hours:
        type: number
        description: Plan Hours
      plan_wages:
        type: number
        description: Plan Wages
      planned_count:
        type: number
        description: Planned Count
      projected_count:
        type: number
        description: Projected Count
      projected_revenue:
        type: number
        description: Projected Revenue
      projected_transactions:
        type: number
        description: Projected Transactions. Only applicable to Location
      scheduled_hours:
        type: number
        description: Scheduled Hours
      scheduled_wages:
        type: number
        description: Scheduled Wages
      taxes_and_benefits_rate:
        type: number
        description: Rate of Benefits and Taxes
      wage_percent:
        type: number
        description: Percent of Wage. Only applicable to Location
