swagger: "2.0"
info:
  description: Returns default recipe data
  version: 1.0.0
  title: Recipes
host: qa-marko.aramark.net
basePath: /v1/product
schemes:
- https
tags:
- name: Recipes
  description: Master Data for an individual recipe and ingredients
paths:
  /recipe:
    get:
      description: Returns master data for an individual recipe and the ingredients that are used
      operationId: getMasterRecipes
      produces:
      - application/json
      tags:
        - Recipes
      parameters:
        - name: recipe_id
          in: query
          type: string
          description: ID used to identify a recipe
          required: true
        - name: master_system_id
          in: query
          type: string
          description: Unique ID of Master System, given that recipe IDs are not unique
          required: false
        - name: bypass-cache
          in: header
          type: string
          description: This HTTP Header variable will bypass cache.
          enum: ['true','false']
          default: false
        - name: apikey
          in: header
          type: string
          description: This HTTP Header variable will verify permissions. 
        - name: smoke
          in: header
          type: string
          description: When set to 'true' this HTTP header variable will route the API call to the Integration testing environment.  Only applicable in QA.
          default: false
      responses:
        200:
          description: List all Menu Items for Location, Service Data and Meal Period.
          schema:
            type: object
            properties:
              status: 
                type: string
                description: ENUM 'Success', 'Error' or 'Not Found'
              count:
                type: string
                description: Number of records returned in request
              master_recipe:
                type: array
                items:
                  $ref: "#/definitions/recipe"
        404:
          description: Requested resource does not exist.
        405:
          description: HTTP Verb / Operation not supported
definitions:
  recipe:
    type: object
    properties:
      recipe_id: 
        type: string
        description: PRIMA Recipe ID
      recipe_name:
        type: string
        description: PRIMA Recipe name of Menu Items
      serving_size_display:
        type: string
        description: Serving Size Description
      uom_system:
        type: string
        description: What Unit of measurement system is being used
      special_instructions:
        type: string
        description: Special Instructions
      assembly_instructions:
        type: string
        description: Assembly Instructions
      ingredients:
        type: array
        items:
          $ref: '#/definitions/ingredients'
  ingredients:
    type: object
    properties:
      ingredient_id: 
        type: string
        description: PRIMA Recipe Ingredient ID
      ingredient_name:
        type: string
        description: PRIMA Recipe Ingredient Name
      ingredient_size_display:
        type: string
        description: Dispaly value of ingredient
      unit_of_measure_id:
        type: string
        description: Unit of measure type ID
      unit_of_measure:
        type: string
        description: Unit of measure description
      amount_needed:
        type: number
        description: Ingredient amount per serving
      prep_tech:
        type: string
        description: Preparation Technique (Nullable)
      prep_method:
        type: string
        description: Preparation Method (Nullable)
      sub_assembly_id: 
        type: string
        description: PRIMA Recipe ID if Ingredient is a sub-assembly (Nullable)
      is_lb_threshold:
        type: string
        description: Y/N is ingredient lb threshold
      ozw_per_tsp:
        type: string
        description: Decimal factor used for conversion of Once Weight (Nullable)
