swagger: "2.0"
info:
  description: This API will return a collection of Recipes for decoration application.
  version: 1.0.0
  title: Recipe Decorations
host: qa-marko.aramark.net
basePath: /v1
schemes:
- https

# Tags organize operations into groups for presentation in the Swagger UI.
# Each tag has an optional description, which the Swagger UI will display in 
# the tag group header.
tags:
- name: Recipe Decorations
  description: Service to provide a collection of Recipes and core attribution for the Front Line Enablement Application

paths:

  # Each Path Item Object describes a resource, containing a set of operations
  # at a specified path.  The Path Item object can define parameters and 
  # responses common all of its contained operations.
  /recipe_decorations:
    
    # Operations are identified by an HTTP method.  
    get:
      description: Returns a collection of Recipes for decoration base on Search or Recipe Id. 
      operationId: getRecipeDecorations
      produces:
      - application/json
      parameters:
        - name: recipe_id
          in: query
          type: string
          description: Unique ID of Recipe from Prima Web
          required: false
        - name: search
          in: query
          type: string
          description: Sting used to search for recipe by name
          required: false
        - name: is_alsr
          type: string
          in: query
          description: Indicator of whether alsr is enabled
          enum: ['Y','N']
          required: false
        - name: is_mm2
          in: query
          type: string
          description: Indicator of whether Master the Menu 2 or mm2 is enabled
          enum: ['Y','N']
          required: false
        - name: is_retail
          in: query
          type: string
          description: Indicator of whether Retail is enabled
          enum: ['Y','N']
        - name: is_smi
          in: query
          type: string
          description: Indicator of whether smi is enabled
          enum: ['Y','N']
        - name: is_harvest_table
          in: query
          type: string
          description: Indicator of when recipe is for Harvest Table menu
          enum: ['Y','N']
        - name: is_patient
          in: query
          type: string
          description: Indicator of when recipe is for patient services
          enum: ['Y','N']
        - name: is_true_eats
          in: query
          type: string
          description: Indicator of when recipe is for True Eats menu
          enum: ['Y','N']
        - name: is_residential
          in: query
          type: string
          description: Indicator of whether Residential is enabled
          enum: ['Y','N']
        - name: fields
          in: query
          type: string
          description: Comma delimited list to reduce the fields of response object. When used the property "recipe_id" will always be appended to the list for a consistent field for response testing.
          required: false
        - name: page
          in: query
          type: string
          description: Page number of data set to return
          default: 1
          required: false
        - name: size
          in: query
          type: string
          description: Number of rows in each page to return.
          default: 50
          required: false
        - name: bypass-cache
          in: header
          type: string
          description: This HTTP Header variable will bypassDo not cache call
          enum: ['true','false']
          default: false
        - name: apikey
          in: header
          type: string
          description: This HTTP Header variable will verify permissions. 
          default: dcF1wtqbCH6bgZ1mVASiGUu6mu8rS8YA
        - name: smoke
          in: header
          type: string
          description: When set to 'true' this HTTP header variable will route the API call to the Integration testing environment.  Only applicable in QA.
          default: false
      tags:
        - Recipe Decorations
      responses:
        200:
          description:
            List all recipe decorations.
          schema:
            type: object
            properties:
              status:
                type: string
                description: ENUM 'Success' or 'Error'
                default: Success
              count:
                type: string
                description: Number of records returned in request
              page:
                type: string
                description: Page number of result set
                default: "1"
              size:
                type: string
                description: Number of records returned with the result set
              recipe_decorations:
                type: array
                items:
                  $ref: "#/definitions/recipe_decorations"
        404:
          description: Requested resource does not exist.
        405:
          description: HTTP Verb / Operation not supported

# The definitions section contains a set of named Schema Objects.  Each schema
# object describes a reusable data type, which can be reference by name.
definitions:
# recipe_decorations definition
  recipe_decorations:
    type: object
    properties:
      master_system_id:
        type: number
        description: ID for the master system source
      recipe_id:
        type: string
        description: Recipe ID coming from source system Prima Web.
      recipe_name:
        type: string
        description: name of recipe
      recipe_marketing_name:        
        type: string
        description: name of recipe
      is_alsr:
        type: string
        description: Indicator of whether alsr is enabled 'Y/N'
      is_mm2:
        type: string
        description: Indicator of whether Master the Menu 2 or mm2 is enabled 'Y/N'
      is_residential:
        type: string
        description: Indicator of whether Recipe is Residential enabled 'Y/N'
      is_retail:
        type: string
        description: Indicator of whether is Retail enabled 'Y/N'
      is_smi:
        type: string
        description: Indicator of whether smi is enabled 'Y/N'
      is_harvest_table:
        type: string
        description: Indicator of when recipe is for Harvest Table menu; 'Y/N' 
      is_patient:
        type: string
        description: Indicator of when recipe is for patient services; 'Y/N' 
      is_true_eats:
        type: string
        description: Indicator of when recipe is for True Eats menu; 'Y/N' 

