swagger: "2.0"
info:
  description: This API will return Weekly Over Production Data
  version: 1.0.0
  title: Weekly Overproduction
host: qa-marko.aramark.net
basePath: /v1/service/weekly
schemes:
- https
paths:
  /overproduction:
    get:
      description: Returns ALL Weekly Overproduction Data for Rolling Weeks
      operationId: getWeeklyOverproduction
      tags:
      - Weekly Overproduction
      produces:
      - application/json
      parameters:
        - in: query 
          name: start_date        
          type: string
          description: Calendar date for fiscal week to roll backwards. "mm/dd/yyyy"
          required: true
        - in: query 
          name: rolling_weeks        
          type: integer
          description: This attribute will take week your date falls in and subtracts the number provided (start week - rolling_weeks) 
          default: 0
          required: false
        - name: bypass-cache
          in: header
          type: string
          description: This HTTP Header variable will bypass cache.
          enum: ['true', 'false']
          default: false
        - name: apikey
          in: header
          type: string
          description: This HTTP Header variable will verify permissions. 
          default: dcF1wtqbCH6bgZ1mVASiGUu6mu8rS8YA
        - name: smoke
          in: header
          type: string
          description: When set to 'true' this HTTP header variable will route the API call to the Integration testing environment.  Only applicable in QA.
          default: false
      responses:
        200:
          description: Provides the Over Production Measure Data
          schema:
            type: object
            properties:
              status:
                type: string
                description: ENUM 'Success', 'Error' or 'Not Found'
                default: Success
              count:
                type: integer
                description: Number of records being returned
              measure:
                type: array
                items:
                 $ref: '#/definitions/measure'
        404:
          description: Requested resource does not exist.
        405:
          description: HTTP Verb / Operation not supported
  /overproduction/{org_value}:
    get:
      description: Returns ALL Weekly Over Production Data for Rolling Weeks
      operationId: getWeeklyOverproductionByOrgValue
      tags:
      - Weekly Overproduction
      produces:
      - application/json
      parameters:
        - in: path
          name: org_value
          type: string
          description: Business Organization Code for return data.
          required: true
        - in: query 
          name: start_date        
          type: string
          description: Calendar date for fiscal week to roll backwards. "mm/dd/yyyy"
          required: true
        - in: query 
          name: rolling_weeks        
          type: integer
          description: This attribute will take week your date falls in and subtracts the number provided (start week - rolling_weeks) 
          default: 0
          required: false
        - name: bypass-cache
          in: header
          type: string
          description: This HTTP Header variable will bypass cache.
          enum: ['true', 'false']
          default: false
        - name: apikey
          in: header
          type: string
          description: This HTTP Header variable will verify permissions. 
          default: dcF1wtqbCH6bgZ1mVASiGUu6mu8rS8YA
        - name: smoke
          in: header
          type: string
          description: When set to 'true' this HTTP header variable will route the API call to the Integration testing environment.  Only applicable in QA.
          default: false
      responses:
        200:
          description: Provides the Over Production Measure Data
          schema:
            type: object
            properties:
              status:
                type: string
                description: ENUM 'Success', 'Error' or 'Not Found'
                default: Success
              count:
                type: integer
                description: Number of records being returned
              measure:
                type: array
                items:
                 $ref: '#/definitions/measure'
        404:
          description: Requested resource does not exist.
        405:
          description: HTTP Verb / Operation not supported

definitions:
  measure:
    type: object
    properties:
      measure_name:
        type: string
        description: Measure Description
      fiscal_period:
        type: string
        description: Fiscal Month of data
      fiscal_week_no:
        type: integer
        description: Fiscal Week of Month
      fiscal_week_id:
        type: integer
        description: Fiscal Day of Week
      org_value:
        type: string
        description: Aramark Organization code for rollup
      org_name:
        type: string
        description: Name or Aramark Organization rollup
      actual_amount:
        type: number
        description: Actual Productive Dollars
