swagger: "2.0"
info:
  description: This API will return a collection of Service Production Areas by Site
  version: 1.0.0
  title: Service Production Areas
host: qa-marko.aramark.net
basePath: /v1/service
schemes:
- https
tags:
- name: Production Areas
  description: Service Production Areas by Site
paths:
  /production_areas:
    get:
      description: Returns Service Production Areas with a given Site ID
      operationId: getServiceProductionAreas
      produces:
      - application/json
      tags:
        - Production Areas
      parameters:
        - name: site_id
          in: query
          type: string
          description: Unique ID of Site
          required: true
        - name: bypass-cache
          in: header
          type: string
          description: This HTTP Header variable will bypass cache.
          enum: ['true', 'false']
          default: false
        - name: apikey
          in: header
          type: string
          description: This HTTP Header variable will verify permissions. 
          default: dcF1wtqbCH6bgZ1mVASiGUu6mu8rS8YA
        - name: smoke
          in: header
          type: string
          description: When set to 'true' this HTTP header variable will route the API call to the Integration testing environment.  Only applicable in QA.
          default: false
      responses:
        200:
          description: List all Production Areas for a Site
          schema:
            type: object
            properties:
              status:
                type: string
                description: ENUM 'Success', 'Error' or 'Not Found'
              count:
                type: string
                description: Number of records returned in request
              production_areas:
                type: array
                items:
                  # Reference to a Schema Object described in 'definitions' section
                  $ref: "#/definitions/production_areas"
        404:
          description: Requested resource does not exist.
        405:
          description: HTTP Verb / Operation not supported
# The definitions section contains a set of named Schema Objects.  Each schema
# object describes a reusable data type, which can be reference by name.
definitions:
  production_areas:
    type: object
    properties:
      site_id:
        type: number
        description: unique identifier of a site
      site_name:
        type: string
        description: name of a site
      profit_center:
        type: string
        description: organization code of the profit center
      profit_center_name: 
        type: string
        description: name of the profit center
      location_id:
        type: number
        description: unique identifier of a location
      location_name:
        type: string
        description: name of a location
      service_area_id:
        type: number
        description: Unique code for a Service Area, sourced by PRIMA and kept for backwards compatibility, will be DEPRECATED   
      service_area_name:
        type: string
        description: Service Area descriptive name
      production_area_id:
        type: number
        description: unique identifier of a prouction area
      production_area_name:
        type: string
        description: name of a production area
