swagger: "2.0"
info:
  description: This API will return a collection of Prima Units of Measure for menu items and recipes
  version: 1.0.0
  title: Units of Measure
host: qa-marko.aramark.net
basePath: /v1/recipe
schemes:
- https
# Tags organize operations into groups for presentation in the Swagger UI.
# Each tag has an optional description, which the Swagger UI will display in 
# the tag group header.
tags:
- name: Units of Measure
  description: Get Units of Measure
paths:
  /units_of_measure:
    # Operations are identified by an HTTP method.  
    get:
      description: Returns a units of measure results
      operationId: getUnitsOfMeasure
      produces:
      - application/json
      parameters:
        - in: query 
          name: uom_id        
          type: string
          description: Unique ID of Recipe Unit of Measure
          required: false
        - name: fields
          in: query
          type: string
          description: Comma delimited list to reduce the fields of response object.  When used the property "uom_id" will always be appended to the list for a consistent field for response testing.
          required: false
        - name: bypass-cache
          in: header
          type: string
          description: This HTTP Header variable will bypass cache.
          enum: ['true', 'false']
          default: false
        - name: apikey
          in: header
          type: string
          description: This HTTP Header variable will verify permissions. 
          default: dcF1wtqbCH6bgZ1mVASiGUu6mu8rS8YA
        - name: smoke
          in: header
          type: string
          description: When set to 'true' this HTTP header variable will route the API call to the Integration testing environment.  Only applicable in QA.
          default: false
      tags:
        - Units of Measure
      responses:
        200:
          description: Provides units of measure
          schema:
            type: object
            properties:
              status:
                type: string
                description: ENUM 'Success', 'Error' or 'Not Found'
              count:
                type: string
                description: Number of records returned by request
              unit_of_measure:
                type: array
                items:
                  # Reference to a Schema Object described in 'definitions' section
                  $ref: "#/definitions/units_of_measure"
        404:
          description: Requested resource does not exist.
        405:
          description: HTTP Verb / Operation not supported

# The definitions section contains a set of named Schema Objects.  Each schema
# object describes a reusable data type, which can be reference by name.
definitions:
  units_of_measure:
    type: object
    properties:
      uom_id:
        type: string
        description: Unit of measure ID from Prima
      description:
        type: string
        description: Unit of measure description
      uom_type:
        type: string
        description: Unit of measure type ie. COUNT, VOLUME, WEIGHT
      ozw_factor:
        type: number
        description: Decimal factor used for conversion of Once Weight
      grams_factor:
        type: number
        description: Decimal factor used for conversion of grams
      tsp_factor:
        type: number
        description: Decimal factor used for conversion of teaspoons
      ml_factor:
        type: number
        description: Decimal factor used for conversion of milliliters
      standard_flag:
        type: string
        description: Y/N is unit of measure in standard format
      metric_flag:
        type: string
        description: Y/N is unit of measure in metric format
      uom_cut_flag:
        type: string
        description: Y/N is unit of measure in cut size

