swagger: "2.0"
info:
  description: This API will return a collection of Menu Items for a specific Location, Service Date and Meal Period.
  version: 1.0.1
  title: Service Menu Items
host: qa-marko.aramark.net
basePath: /v1
schemes:
- https

# Tags organize operations into groups for presentation in the Swagger UI.
# Each tag has an optional description, which the Swagger UI will display in 
# the tag group header.
tags:
- name: Service Menu Items
  description: An individual Service Menu and its Items for a Location and Service Date

paths:

  # Each Path Item Object describes a resource, containing a set of operations
  # at a specified path.  The Path Item object can define parameters and 
  # responses common all of its contained operations.
  /service_menu_items:

    # Operations are identified by an HTTP method.  
    get:
      description: Returns a Hierarchal collection of Menu Items for a Service Menu. This interfaces requires either location_id,  service_area_id or sub_location_id to be provided.
      operationId: getServiceMenuItems
      produces:
      - application/json
      tags:
        - Service Menu Items
      parameters:
        - name: service_date
          in: query
          type: string
          description: Service Date in Format "mm/dd/yyyy"
          required: true
        - name: location_id
          in: query
          type: string
          description: Unique ID of Location to return Menus.
          required: false
        - name: service_area_id
          in: query
          type: string
          description: Unique ID of Service Area for a Service Date.
          required: false
        - name: sub_location_id
          in: query
          type: string
          description: Unique ID of Sub Location aka Station for a Service Date.
          required: false
        - name: meal_period_id
          in: query
          type: string
          description: Unique ID of Meal Period for a Location and Service Date.
          required: false
        - name: is_mto
          in: query
          type: string
          description: Filter for Made to Order Menu Items.
          enum: ['Y','N']
          required: false
        - name: is_result_required
          in: query
          type: string
          description: Filter for menu results required for Menu Items.
          enum: ['Y','N']
          required: false
        - name: is_temp_required
          in: query
          type: string
          description: Filter for Menu Items which require temperature readings.
          enum: ['Y','N']
          required: false
        - name: bypass-cache
          in: header
          type: string
          description: This HTTP Header variable will bypass cache.
          enum: ['true', 'false']
          default: false
        - name: apikey
          in: header
          type: string
          description: This HTTP Header variable will verify permissions. 
          default: dcF1wtqbCH6bgZ1mVASiGUu6mu8rS8YA
        - name: smoke
          in: header
          type: string
          description: When set to 'true' this HTTP header variable will route the API call to the Integration testing environment.  Only applicable in QA.
          default: false
      responses:
        200:
          description: List all Menu Items for Location, Service Data and Meal Period.
          schema:
            type: object
            properties:
              status:
                type: string
                description: ENUM 'Success', 'Not Found' or 'Error'
              count:
                type: string
                description: Number of records returned in request
              service_menus:
                type: array
                items:
                  # Reference to a Schema Object described in 'definitions' section
                  $ref: "#/definitions/service_menus"
        404:
          description: Requested resource does not exist.
        405:
          description: HTTP Verb / Operation not supported

  /service_menu_items/flat:

    # Operations are identified by an HTTP method.  
    get:
      description: This sub-domain is used to return a flat response object and can also be used to limit the fields being returned by the API (Ad hoc). This interfaces requires either location_id,  service_area_id or sub_location_id to be provided. 
      operationId: getServiceMenuItemsFlat
      produces:
      - application/json
      tags:
        - Service Menu Items
      parameters:
        - name: service_date
          in: query
          type: string
          description: Service Date in Format "mm/dd/yyyy"
          required: true
        - name: location_id
          in: query
          type: string
          description: Unique ID of Location to return Menus.
          required: false
        - name: service_area_id
          in: query
          type: string
          description: Unique ID of Service Area for a Service Date.
          required: false
        - name: sub_location_id
          in: query
          type: string
          description: Unique ID of Sub Location aka Station for a Service Date.
          required: false
        - name: meal_period_id
          in: query
          type: string
          description: Unique ID of Meal Period for a Location and Service Date.
          required: false
        - name: fields
          in: query
          type: string
          description: Comma delimited list to reduce the fields of response object.  When used the property "location_id" will always be appended to the list for a consistent field for response testing.
          required: false
        - name: is_mto
          in: query
          type: string
          description: Filter for Made to Order Menu Items.
          enum: ['Y','N']
          required: false
        - name: is_result_required
          in: query
          type: string
          description: Filter for menu results required for Menu Items.
          enum: ['Y','N']
          required: false
        - name: is_temp_required
          in: query
          type: string
          description: Filter for Menu Items which require temperature readings.
          enum: ['Y','N']
          required: false
        - name: bypass-cache
          in: header
          type: string
          description: This HTTP Header variable will bypass cache.
          enum: ['true', 'false']
          default: false
        - name: apikey
          in: header
          type: string
          description: This HTTP Header variable will verify permissions. 
          default: dcF1wtqbCH6bgZ1mVASiGUu6mu8rS8YA
        - name: smoke
          in: header
          type: string
          description: When set to 'true' this HTTP header variable will route the API call to the Integration testing environment.  Only applicable in QA.
          default: false
      responses:
        200:
          description: List all Menu Items for Location, Service Data and Meal Period.
          schema:
            type: object
            properties:
              status:
                type: string
                description: ENUM 'Success', 'Error' or 'Not Found'
              count:
                type: string
                description: Number of records returned in request
              service_items:
                type: array
                items:
                  # Reference to a Schema Object described in 'definitions' section
                  $ref: "#/definitions/service_items"
        404:
          description: Requested resource does not exist.
        405:
          description: HTTP Verb / Operation not supported
# The definitions section contains a set of named Schema Objects.  Each schema
# object describes a reusable data type, which can be reference by name.
definitions:
# Structure for Hierarchal Response
#  Aramark:
#    type: object
#    properties:
#      status:
#        type: string
#        description: ENUM 'Success', 'Error' or 'Not Found'
#        default: Success
#      count:
#        type: string
#        description: Number of Records return in request
#      service_menus:
#        type: array
#        items:
#          $ref: '#/definitions/service_menus'

# Structure for Ad hoc Response
#  AramarkFlat:
#    type: object
#    properties:
#      status:
#        type: string
#        description: ENUM 'Success', 'Error' or 'Not Found'
#        default: Success
#      count:
#        type: string
#        description: Number of Records return in request
#      service_items:
#        type: array
#        items:
#          $ref: '#/definitions/service_items'
  service_menus:
    type: object
    properties:
      menu:
        type: array
        items:
          $ref: '#/definitions/menu'

  menu:
    type: object
    properties:
      location_id:
        type: integer
        description: Unique code for a Location, sourced by BIC or MDG      
      location_name:
        type: string
        description: Location descriptive name
      location:
        type: string
        description: Unique code for a Location, sourced by MDG
      service_area_id:
        type: integer
        description: Unique code for a Service Area, sourced by PRIMA and kept for backwards compatibility, will be DEPRECATED        
      service_area_name:
        type: integer
        description: Service Area descriptive name
      service_menu_id:
        type: integer
        description: Unique ID of Service Menu
      service_date:
        type: string
        description: Calendar date of service in 'MM/DD/YYYY' format
      meal_period_id:
        type: integer
      meal_period_name: 
        type: string
      sub_locations:
        type: array
        items:
          $ref: '#/definitions/sub_locations'
  
  sub_locations:
    type: object
    properties:
      sub_location_id:
        type: integer
        description: Unique code for a Sub Location, sourced by PRIMA or MDG        
      sub_location_name:
        type: string
        description: Sub Location descriptive name
      sub_location:
        type: string
        description: Unique code for a Sub Location, sourced by MDG
#      sub_location_type_id:
#        type: string
#        description: Unique code for a Sub Location Types, sourced by MDG
#      sub_location_type:
#        type: string
#        description: Description of Sub Location Types, sourced by MDG
      menu_items:
        type: array
        items:
          $ref: '#/definitions/menu_items'
  menu_items:
    type: object
    properties:
      service_menu_item_id:
        type: integer
        description: Unique ID of Service Menu Item
      master_system_id: 
        type: integer
      recipe_id: 
        type: string
        description: PRIMA Recipe ID, required master_system_id and recipe_id for uniqueness.
      recipe_name:
        type: string
        description: PRIMA Recipe name of Menu Items
      recipe_marketing_name:
        type: string
        description: PRIMA Recipe marketing name of Menu Items
      recipe_short_name:
        type: string
        description: Alternate name used for Recipe, driven by Marketing or Operations
      production_area_id:
        type: string
        description: Unique ID of the Production Area
      production_area_name:
        type: string
        description: Production Area descriptive name
      is_mto: 
        type: string 
        description: Enumerator of 'Y' or 'N' to indicate that the Item is a 'Made to Order" recipe
      is_temp_required: 
        type: string 
        description: Enumerator of 'Y' or 'N' to determine if the menu item should be checked regularly to ensure that the item is within safe temperature range.
      serving_size_uom_id:
        type: string
      serving_size_number: 
        type: integer
        description: Portion Size (integer portion)
      serving_size_description:
        type: string
        description: Portion Size Unit of Measure Description
      serving_size_fraction_id:
        type: string
      serving_size_fraction_description:
        type: string
        description: Portion Size Fraction Description
      serving_size_display:
        type: string
        description: Serving Size Description
      food_cost:
        type: number
        description: Local food cost of item
      acceptability_factor:
        type: number
        description: Forecast percentage per patron
      planned_count:
        type: number
        description: Planned number of portions per service period
      prep_count:
        type: number
        description: Actual prepared portions
      on_hand_count:
        type: number
        description: Number of portions reused for service
      sold_count:
        type: number
        description: Number of portions sold
      leftover_count:
        type: number
      waste_count:
        type: number
        description: Number of portions wasted
      is_result_required: 
        type: string 
        description: Enumerator of 'Y' or 'N' to determine if the menu item should require a service result.        
      smi_row_no:
        type: number
        description: SMI Number
      comments: 
        type: string 
        description: Menu Item Comments
  service_items:
    type: object
    properties:
      location_id:
        type: integer
        description: Unique code for a Location, sourced by BIC or MDG      
      location_name:
        type: string
        description: Location descriptive name
      location:
        type: string
        description: Unique code for a Location, sourced by MDG
      service_area_id:
        type: integer
        description: Unique code for a Service Area, sourced by PRIMA and kept for backwards compatibility, will be DEPRECATED        
      service_area_name:
        type: integer
        description: Service Area descriptive name
      service_menu_id:
        type: integer
        description: Unique ID of Service Menu
      service_date:
        type: string
        description: Calendar date of service in 'MM/DD/YYYY' format
      meal_period_id:
        type: integer
      meal_period: 
        type: string
      sub_location_id:
        type: integer
        description: Unique code for a Sub Location, sourced by PRIMA or MDG    
      sub_location_name:
        type: string
        description: Sub Location descriptive name
      sub_location:
        type: string
        description: Unique code for a Sub Location, sourced by MDG
      service_menu_item_id:
        type: integer
        description: Unique ID of Service Menu Item
      master_system_id: 
        type: integer
      recipe_id: 
        type: string
        description: PRIMA Recipe ID, required master_system_id and recipe_id for uniqueness.
      recipe_name:
        type: string
        description: PRIMA Recipe name of Menu Items
      recipe_marketing_name:
        type: string
        description: PRIMA Recipe marketing name of Menu Items
      recipe_short_name:
        type: string
        description: Alternate name used for Recipe, driven by Marketing or Operations
      production_area_id:
        type: string
        description: Unique ID of the Production Area
      production_area_name:
        type: string
        description: Production Area descriptive name
      is_mto: 
        type: string 
        description: Enumerator of 'Y' or 'N' to indicate that the Item is a 'Made to Order" recipe
      is_temp_required: 
        type: string 
        description: Enumerator of 'Y' or 'N' to determine if the menu item should be checked regularly to ensure that the item is within safe temperature range.        
      serving_size_uom_id:
        type: string
      serving_size_number: 
        type: integer
        description: Portion Size (integer portion)
      serving_size_description:
        type: string
        description: Portion Size Unit of Measure Description
      serving_size_fraction_id:
        type: string
      serving_size_fraction_description:
        type: string
        description: Portion Size Fraction Description
      serving_size_display:
        type: string
        description: Serving Size Description
      food_cost:
        type: number
        description: Local food cost of item
      acceptability_factor:
        type: number
        description: Forecast percentage per patron
      planned_count:
        type: number
        description: Planned number of portions per service period
      prep_count:
        type: number
        description: Actual prepared portions
      on_hand_count:
        type: number
        description: Number of portions reused for service
      sold_count:
        type: number
        description: Number of portions sold
      leftover_count:
        type: number
      waste_count:
        type: number
        description: Number of portions wasted
      is_result_required: 
        type: string 
        description: Enumerator of 'Y' or 'N' to determine if the menu item should require a service result.        
      smi_row_no:
        type: number
        description: SMI Number
      comments: 
        type: string 
        description: Menu Item Comments              

