openapi: 3.0.0
info:
  description: |

    This API will return Alert Notifications.
    
    __Base URL endpoint for the api in production__: i`https://marko.aramark.net/v1/alerts`.
    
    For testing against the API with the "Try" tool on this page, use either our testing server "qa-marko" or our development server "dev-marko".
  version: "1.0.0-oas3"
  title: Alerts
tags:
  - name: Alerts
    description: Get Daily Profit Center Alerts Aggregate
  - name: Labor
    description: Gets Labor Alert details
  - name: Purchasing
    description: Gets Purchasing Alert details
  - name: Point of Sale
    description: Gets POS Alert details
paths:
  /profit_centers:
    get:
      description: Returns an aggregate of alerts at a Profit Center level
      operationId: getProfitCenterAlerts
      tags:
        - Alerts
      parameters:
        - in: query
          name: user_id
          description: Email address of the manager
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/pageParam'
        - name: size
          in: query
          description: Number of records to be returned in each page of result set
          schema:
            type: string
            default: 50
        - $ref: '#/components/parameters/bypassCacheParam'
        - $ref: '#/components/parameters/smokeParam'
      responses:
        '200':
          description: Provides the labor forecast data
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: 'ENUM ''Success'', ''Error'' or ''Not Found'''
                    default: Success
                  count:
                    type: integer
                    description: Number of records being returned
                  notifications:
                    type: array
                    items: null
                    $ref: '#/components/schemas/notifications'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
  /labor/overtime/{org_value}:
    get:
      description: Returns Labor Daily Overtime Alerts
      operationId: getDailyLaborOvertimeByOrgValue
      tags:
        - Labor
      parameters:
        - $ref: '#/components/parameters/orgValueParam'
        - $ref: '#/components/parameters/startDateParam'
        - $ref: '#/components/parameters/endDateParam'
        - $ref: '#/components/parameters/bypassCacheParam'
        - $ref: '#/components/parameters/smokeParam'
      responses:
        '200':
          description: Provides the labor overtime alerts
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: 'ENUM ''Success'', ''Error'' or ''Not Found'''
                    default: Success
                  count:
                    type: integer
                    description: Number of records being returned
                  overtime_alerts:
                    type: array
                    items:
                      $ref: '#/components/schemas/overtime_alerts'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
  /purchasing/order/{org_value}:
    get:
      description: Returns Purchasing Alerts
      operationId: getPuchasingAlertsByOrgValue
      tags:
        - Purchasing
      parameters:
        - $ref: '#/components/parameters/orgValueParam'
        - $ref: '#/components/parameters/startDateParam'
        - $ref: '#/components/parameters/endDateParam'
        - $ref: '#/components/parameters/bypassCacheParam'
        - $ref: '#/components/parameters/smokeParam'
      responses:
        '200':
          description: Provides the purchasing order alerts
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: 'ENUM ''Success'', ''Error'' or ''Not Found'''
                    default: Success
                  count:
                    type: integer
                    description: Number of records being returned
                  purchasing_order_alerts:
                    type: array
                    items:
                      $ref: '#/components/schemas/purchasing_order_alerts'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
  /pos/{org_value}:
    get:
      description: Returns Point of Sale Alerts
      operationId: getPOSAlertsByOrgValue
      tags:
        - Point of Sale
      parameters:
        - $ref: '#/components/parameters/orgValueParam'
        - $ref: '#/components/parameters/startDateParam'
        - $ref: '#/components/parameters/endDateParam'
        - $ref: '#/components/parameters/bypassCacheParam'
        - $ref: '#/components/parameters/smokeParam'
      responses:
        '200':
          description: Provides the point of sale alerts
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: 'ENUM ''Success'', ''Error'' or ''Not Found'''
                    default: Success
                  count:
                    type: integer
                    description: Number of records being returned
                  point_of_sale_alerts:
                    type: array
                    items:
                      $ref: '#/components/schemas/point_of_sale_alerts'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
servers:
  - url: https://{environment}.aramark.net/v1/alerts
    variables:
      environment:
        description: >
          Server choices:
           * `qa-marko` QA server, is the default.
           * `dev-marko` Development server.
        default: qa-marko # Testing server 
        enum:
          - dev-marko     # Development server
          - qa-marko      # Staging server
components:
  parameters:
    orgValueParam:
      in: path
      name: org_value
      description: provide business organization code in URL to filter data set
      required: true
      schema:
        type: string
    pageParam:
      in: query
      name: page
      description: Page number of result set
      required: false
      schema:
        type: number
        default: 1
    startDateParam:
      in: query
      name: start_date
      description: Calendar date for daily transactions. "mm/dd/yyyy"
      required: false
      schema:
        type: string
    endDateParam:
      in: query
      name: end_date
      description: >-
        Calendar date end date for daily transactions. Will use start_date if
        not provided. "mm/dd/yyyy"
      required: false
      schema:
        type: string
    bypassCacheParam:
      in: header
      name: bypass-cache
      description: This HTTP Header variable will bypass cache.
      schema:
        type: string
        enum:
          - 'true'
          - 'false'
        default: false
    smokeParam:
      in: header
      name: smoke
      description: >-
        When set to 'true' this HTTP header variable will route the API call to
        the Integration testing environment.  Only applicable in QA.
      schema:
        type: string
        default: false
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: apiKey
      description: This HTTP Header variable will verify permissions.
  schemas:
    notifications:
      type: object
      properties:
        profit_center:
          type: string
          description: Aramark Organization code
        profit_center_name:
          type: string
          description: Name of the Profit Center
        alerts:
          type: array
          items:
            $ref: '#/components/schemas/alerts'
    alerts:
      type: object
      properties:
        type:
          type: string
          description: description of the type of alert
          enum:
            - LABOR
            - PURCHASE ORDER
            - POINT OF SALES
        value:
          type: number
          description: value of the alert
    overtime_alerts:
      type: object
      properties:
        trigger_date:
          type: string
          description: Date of alert
        overtime_date:
          type: string
          description: Date that overtime will start for employee
        profit_center:
          type: string
          description: Aramark Organization code for rollup
        profit_center_name:
          type: string
          description: Name of Aramark Organization rollup
        manager_id:
          type: string
          description: Employee ID of the manager
        manager_first_name:
          type: string
          description: First name of the manager
        manager_last_name:
          type: string
          description: Last name of the manager
        manager_email:
          type: string
          description: Email address of the manager
        employee_id:
          type: string
          description: Employee ID of the employee
        employee_first_name:
          type: string
          description: First name of the employee
        employee_last_name:
          type: string
          description: Last name of the employee
        active:
          type: string
          description: Flag indicating whether or not the alert is active
        update_date:
          type: string
          description: Date and Time of the most recent refresh of data
    purchasing_order_alerts:
      type: object
      properties:
        ordered_date:
          type: string
          description: Date the order was placed
        need_by_date:
          type: string
          description: Date the order is needed by
        profit_center:
          type: string
          description: Aramark Organization code for rollup
        profit_center_name:
          type: string
          description: Name of Aramark Organization rollup
        order_id:
          type: string
          description: Unique identifier of the purchase order
        status:
          type: string
          description: Current status of the order
          enum:
            - Ordered
            - Receiving
        time_updated:
          type: string
          description: Timestamp of the last change in order status
        preparer:
          type: string
          description: Email address of individual who prepared the order
        update_date:
          type: string
          description: Date and Time of the most recent refresh of data
    point_of_sale_alerts:
      type: object
      properties:
        profit_center:
          type: string
          description: Aramark Organization code for rollup
        profit_center_name:
          type: string
          description: Name of Aramark Organization rollup
        location_code:
          type: string
          description: Location Code for rollup
        location_name:
          type: string
          description: Name of Aramark location
        source_system:
          type: string
          description: Name of the POS system
        business_date:
          type: string
          description: Date the alert was generated
        employee_id:
          type: number
          description: Employee ID of the employee
        first_name:
          type: string
          description: First name of the employee
        last_name:
          type: string
          description: Last name of the employee
        alert_description:
          type: string
          description: Description of the alert generated by the employee
        alert_name:
          type: string
          description: Name of the alert generated by the employee
        display_name:
          type: string
          description: Name of the alert generated by the employee for display purposes
        number_of_alerts:
          type: number
          description: Total number of alerts for the employee
        service_type_description:
          type: string
          description: Description of the type of service at the location
        update_date:
          type: string
          description: Date and Time of the most recent refresh of data
