openapi: 3.0.0
info:
  description: | 
    
    Given a day or date range this API has methods to list:
      * fiscal day attributes
      * operational day attributes

    You can return return the _calendar dates_ for given fiscal day attributes:

       * fiscal year
       * fiscal month
       * week of a fiscal month
       * day of the week in a fiscal month

      **The Aramark Fiscal Year**

       * The first month of the fiscal year is October
       * Fiscal months rarely begin on the first day of their correspoinding calendar month. They range in starting from several days before the beginning of their namesake calendar month to several days after.
       * October, November, January, February, April, May, July, and August always have 28 days
       * December, March, and June always have 35 days
       * September usually has 35 days except in the following years when it has 42 days: 2020, 2025, 2031, 2036, 2042, and 2048
       * All years, months and weeks begin on Saturday

    __The base endpoint URL for this API in production is:__ `https://marko.aramark.net/v1`.

    For testing the API with the "Try" tool on this page or in your app, use either our testing server "qa-marko" or our development server "dev-marko".

  version: "1.0.0-oas3"
  title: Calendar
tags:
  - name: Calendar Day
  - name: Fiscal Day
  - name: Operational Day
security:
  - apiKey: []
paths:
  /calendar/day:
    get:
      summary: Calendar dates for fiscal params
      description: |

        Return a list of calendar dates that meet spefic fiscal time creiteria. 
        
        At a minimum you must specify fiscal_year or fiscal_period (e.g. month).

        ![This endpoint is in production](/themes/portal/images/statuspngs/statusprod.png)
      operationId: getCalendarDay
      parameters:
        - $ref: '#/components/parameters/fiscalYearParam'
        - $ref: '#/components/parameters/fiscalPeriodParam'
        - $ref: '#/components/parameters/fiscalWeekOfMonthParam'
        - $ref: '#/components/parameters/fiscalDayOfWeekParam'
        - $ref: '#/components/parameters/bypassCacheParam'
        - $ref: '#/components/parameters/smokeParam'
      tags:
        - Calendar Day
      responses:
        '200':
          description: List of calendar day information
          content:
            '*/*':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ENUM 'Success' or 'Error'
                    default: Success
                  count:
                    type: string
                    description: Number of calendar dates returned
                  calendar_dates:
                    type: array
                    items:
                      $ref: '#/components/schemas/calendar_dates'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
  /fiscal/day:
    get:
      summary: Fiscal day attributes
      description: |

        Return fiscal day attributes for given calendar dates

        ![This endpoint is in production](/themes/portal/images/statuspngs/statusprod.png)
      operationId: getFiscalDay
      parameters:
        - $ref: '#/components/parameters/startDateParam'
        - $ref: '#/components/parameters/endDateParam'
        - $ref: '#/components/parameters/fieldsParam'
        - $ref: '#/components/parameters/bypassCacheParam'
        - $ref: '#/components/parameters/smokeParam'
      tags:
        - Fiscal Day
      responses:
        '200':
          description: List of fiscal day information
          content:
            '*/*':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ENUM 'Success' or 'Error'
                    default: Success
                  count:
                    type: string
                    description: Number of records returned in request
                  fiscal_day:
                    type: array
                    items:
                      $ref: '#/components/schemas/fiscal_day'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported

  /operational/day:
    get:
      summary: Operational day attributes
      description: |

        Return operational day information for given calendar dates.

        ![This endpoint is in production](/themes/portal/images/statuspngs/statusprod.png)
      operationId: getOperationalDay

        For testing the API with the "Try" tool on this page or in your app, use either our testing server "qa-marko" or our development server "dev-marko".
      parameters:
        - $ref: '#/components/parameters/startDateParam'
        - $ref: '#/components/parameters/endDateParam'
        - $ref: '#/components/parameters/fieldsParam'
        - $ref: '#/components/parameters/bypassCacheParam'
        - $ref: '#/components/parameters/smokeParam'
      tags:
        - Operational Day
      responses:
        '200':
          description: List of fiscal day information
          content:
            '*/*':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ENUM 'Success' or 'Error'
                    default: Success
                  count:
                    type: string
                    description: Number of records returned in request
                  operational_day:
                    type: array
                    items:
                      $ref: '#/components/schemas/operational_day'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
servers:
  - url: https://qa-marko.aramark.net/v1
    description: Testing server
  - url: https://dev-marko.aramark.net/v1
    description: Development server
components:
  parameters:
    startDateParam:
      in: query
      name: start_date
      description: Calendar date for daily transactions. "mm/dd/yyyy"
      required: false
      schema:
        type: string
    endDateParam:
      in: query
      name: end_date
      description: >-
        Calendar date end date for daily transactions. Will use start_date if
        not provided. "mm/dd/yyyy"
      required: false
      schema:
        type: string
    fieldsParam:
      in: query
      name: fields
      description: >-
        Comma separated list of output parameters used to limit the output
        model.
      required: false
      schema:
        type: string
    fiscalYearParam:
      in: query
      name: fiscal_year
      description: Fiscal year (e.g. "2021")
      required: false
      schema:
        type: number
    fiscalPeriodParam:
      in: query
      name: fiscal_period
      description: Aramark fiscal month using format "MON_FY-YY" (e.g. "JAN_FY-21")
      required: false
      schema:
        type: string
    fiscalWeekOfMonthParam:
      in: query
      required: false
      name: fiscal_week_of_month
      description: >-
        Week of the fiscal month. Only works when fiscal_period (e.g. month)
        is specified.
      schema:
        type: number
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
    fiscalDayOfWeekParam:
      in: query
      required: false
      name: fiscal_day_of_week
      description: >
        Day of the week. Only works only when fiscal_period (e.g. month)
        _and_ fiscal_week_of_month are specified.
         
         * `1` - Saturday
         * `2` - Sunday
         * `3` - Monday
         * `4` - Tuesday
         * `5` - Wednesday
         * `6` - Thursday
         * `7` - Friday
      schema:
        type: number
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
    bypassCacheParam:
      in: header
      name: bypass-cache
      description: This HTTP Header variable will bypass cache.
      schema:
        type: string
        enum:
          - 'true'
          - 'false'
        default: false
    smokeParam:
      in: header
      name: smoke
      description: >-
        When set to 'true' this HTTP header variable will route the API call to
        the Integration testing environment.  Only applicable in QA.
      schema:
        type: string
        default: false
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: apikey
      description: This HTTP Header variable will verify permissions.
  schemas:
    fiscal_day:
      type: object
      properties:
        calendar_date:
          type: string
          description: Timestamp of calendar date to corresponding fiscal day
        fiscal_day_of_year:
          type: number
          description: numeric value of fiscal day of year
        fiscal_day_of_month:
          type: number
          description: numeric value of fiscal day of month
        fiscal_day_of_quarter:
          type: number
          description: numeric value of fiscal day of quarter
        fiscal_day_of_week:
          type: number
          description: numeric value of fiscal day of week
        fiscal_max_week_in_month:
          type: number
          description: maximum number of weeks in fiscal month
        fiscal_month_abbr:
          type: string
          description: three letter abbreviation for fiscal month
        fiscal_month_id:
          type: number
          description: unique id for the fiscal month
        fiscal_month_name:
          type: string
          description: name of the fiscal month
        fiscal_month_of_year:
          type: number
          description: numeric value of fiscal month of year
        fiscal_month_of_quarter:
          type: number
          description: numeric value of fiscal month of quarter
        fiscal_period:
          type: string
          description: name of the fiscal period
        fiscal_period_week:
          type: string
          description: fiscal period and week
        fiscal_quarter_id:
          type: number
          description: unique id for the fiscal quarter
        fiscal_quarter_name:
          type: string
          description: name of the fiscal quarter
        fiscal_quarter_of_year:
          type: number
          description: numeric value of the fiscal quarter of year
        fiscal_week_day:
          type: string
          description: 'fiscal period, week and day'
        fiscal_week_id:
          type: number
          description: unique id of fiscal week
        fiscal_week_of_month:
          type: number
          description: numeric value of the fiscal week of month
        fiscal_week_of_quarter:
          type: number
          description: numeric value of the fiscal week of quarter
        fiscal_week_of_year:
          type: number
          description: numeric value of the fiscal week of year
        fiscal_year_id:
          type: number
          description: unique id of the fiscal year
        fiscal_year_month:
          type: number
          description: fiscal year and month
        fiscal_year_name:
          type: string
          description: name of the fiscal year
        fiscal_year_number:
          type: string
          description: numeric value of the fiscal year
    calendar_dates:
      type: object
      properties:
        calendar_date:
          type: string
          description: Calendar date for fiscal options provided. "MM/DD/YYYY"
    operational_day:
      type: object
      properties:
        calendar_date:
          type: string
          description: Timestamp of calendar date to corresponding operational day
        operational_afs_period:
          type: string
          description: shorthand description of operational month and year
        operational_day_of_year:
          type: number
          description: numeric value of operational day of year
        operational_day_of_month:
          type: number
          description: numeric value of operational day of month
        operational_day_of_quarter:
          type: number
          description: numeric value of operational day of quarter
        operational_day_of_week:
          type: number
          description: numeric value of operational day of week
        operational_max_week_in_month:
          type: number
          description: maximum number of weeks in operational month
        operational_month_abbr:
          type: string
          description: three letter abbreviation for operational month
        operational_month_id:
          type: number
          description: unique id for the operational month
        operational_month_name:
          type: string
          description: name of the operational month
        operational_month_of_year:
          type: number
          description: numeric value of operational month of year
        operational_month_of_quarter:
          type: number
          description: numeric value of operational month of quarter
        operational_period:
          type: string
          description: name of the operational period
        operational_period_week:
          type: string
          description: operational period and week
        operational_quarter_id:
          type: number
          description: unique id for the operational quarter
        operational_quarter_name:
          type: string
          description: name of the operational quarter
        operational_quarter_of_year:
          type: number
          description: numeric value of the operational quarter of year
        operational_week_day:
          type: string
          description: 'operational period, week and day'
        operational_week_id:
          type: number
          description: unique id of operational week
        operational_week_of_month:
          type: number
          description: numeric value of the operational week of month
        operational_week_of_quarter:
          type: number
          description: numeric value of the operational week of quarter
        operational_week_of_year:
          type: number
          description: numeric value of the operational week of year
        operational_year_id:
          type: number
          description: unique id of the operational year
        operational_year_month:
          type: number
          description: operational year and month
        operational_year_name:
          type: string
          description: name of the operational year
        operational_year_number:
          type: string
          description: numeric value of the operational year
