openapi: 3.0.0
info:
  description: |

    This is a collection of APIs to support Corrections
    
    The base endpoint URL for this API in production is: `https://marko.aramark.net/i1/corrections`.

    For testing the API with the "Try" tool on this page or in your app, use either our testing server "qa-marko" or our development server "dev-marko".
  version: 1.0.0-oas3
  title: Corrections
security:
  - apiKey: []
paths:
# this is what comes after the base path.
  /icare/eligible:
    get:
      operationId: getiCareEligible
      tags:
        - iCare
      summary: Gets iCare Eligibility Data
      parameters:
        - $ref: '#/components/parameters/inmateNodeIdParam'
        - $ref: '#/components/parameters/inmateConcatNumberParam'
        - $ref: '#/components/parameters/canOrderIcareParam'
        - $ref: '#/components/parameters/orderParam'
        - $ref: '#/components/parameters/bypassCacheParam'
      responses:
        '200':
          description: Collection of iCare Eligibility
          content:
            '*/*':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ENUM 'Success' or 'Error'
                    default: Success
                  page:
                    type: number
                  size:
                    type: number
                  count:
                    type: number
                    description: Number of records returned
                  icare_eligible:
                    type: array
                    items:
                      $ref: '#/components/schemas/icare_eligible'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
servers:
# If spec is only in dev, then delete the "Testing Server"
  - url: https://qa-marko.aramark.net/i1/corrections
    description: Testing server
  - url: https://dev-marko.aramark.net/i1/corrections
    description: Development server
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: apikey
      description: This HTTP Header variable will verify permissions.
  parameters:
    inmateNodeIdParam:
      in: query
      name: inmate_nodeid
      description: Inmate Node ID
      required: false
      schema:
        type: string
    inmateConcatNumberParam:
      in: query
      name: iname_concat_number
      description: Concatenated number of the inmate
      required: false
      schema:
        type: string
    canOrderIcareParam:
      in: query
      name: can_order_icare
      description: Indicates if the inmate can order iCare
      required: false
      schema:
        type: boolean
    orderParam:
      in: query
      name: order
      description: Column Name by which to order the result set
      schema:
        type: string
        default: 'INMATE_CONCAT_NUMBER'
    pageParam:
      in: query
      name: page
      description: Page number of result set
      schema:
        type: number
        default: 1
    sizeParam:
      in: query
      name: size
      description: Number of records to be returned in each page of result set
      schema:
        type: string
        default: 50
    bypassCacheParam:
      in: header
      name: bypass-cache
      description: This HTTP Header variable will bypass cache.
      schema:
        type: string
        enum:
          - 'true'
          - 'false'
        default: 'false'
  schemas:
    icare_eligible:
      type: object
      properties:
        inmate_nodeid:
          type: string
        inmate_number:
          type: string
        inmate_secondary_number:
          type: string
        inmate_concat_number:
          type: string
        first_name:
          type: string
        middle_name:
          type: string
        last_name:
          type: string
        full_name:
          type: string
        can_order_icare:
          type: boolean