swagger: "2.0"
info:
  description: This API will return Food Waste Tracking Data
  version: 1.0.0
  title: Daily Food Waste Tracking
host: qa-marko.aramark.net
basePath: /v1/service/daily
schemes:
- https
securityDefinitions:
  apiKeyAuth:
    type: apiKey
    in: header
    name: apikey
    description: This HTTP Header variable will verify permissions.
parameters:
  startDateParam:
    in: query 
    name: start_date        
    type: string
    description: Calendar date for starting range of service dates. "mm/dd/yyyy"
    required: true
  endDateParam:
    in: query 
    name: end_date        
    type: string
    description: Calendar date for ending range of service dates. "mm/dd/yyyy"
    required: true
  sortParam:
    in: query 
    name: sort
    type: string
    description: Result set sorting 
    enum: [ASC, DESC]
    required: false
    default: "ASC"
  bypassCacheParam:
    name: bypass-cache
    in: header
    type: string
    description: This HTTP Header variable will bypass cache.
    enum: ['true', 'false']
    default: false
  smokeParam:
    name: smoke
    in: header
    type: string
    description: When set to 'true' this HTTP header variable will route the API call to the Integration testing environment.  Only applicable in QA.
    default: false
paths:
  /food_waste:
    get:
      description: Returns ALL Daily Service Food Waste
      operationId: getDailyFoodWaste
      tags:
      - Service Daily Food Waste
      produces:
      - application/json
      parameters:
        - $ref: '#/parameters/startDateParam'
        - $ref: '#/parameters/endDateParam'
        - $ref: '#/parameters/sortParam'
        - $ref: '#/parameters/bypassCacheParam'
        - $ref: '#/parameters/smokeParam'
      responses:
        200:
          description: Provides the Service Food Waste Summary Data
          schema:
            type: object
            properties:
              status:
                type: string
                description: ENUM 'Success'
                default: Success
              count:
                type: integer
                description: Number of records being returned
                
              measure:
                type: array
                items:
                  - $ref: '#/definitions/food_waste'
        404:
          description: Requested resource does not exist.
        405:
          description: HTTP Verb / Operation not supported
  /food_waste/{org_value}:
    get:
      description: Rolls up Daily Service Food Waste for a Specific Business Organization
      operationId: getDailyFoodWasteByOrgValue
      tags:
      - Service Daily Food Waste
      produces:
      - application/json
      parameters:
        - in: path 
          name: org_value        
          type: string
          description: Aramark Organization Code 
          required: true
        - $ref: '#/parameters/startDateParam'
        - $ref: '#/parameters/endDateParam'
        - $ref: '#/parameters/sortParam'
        - $ref: '#/parameters/bypassCacheParam'
        - $ref: '#/parameters/smokeParam'
      responses:
        200:
          description: Provides the Service Food Waste Summary Data
          schema:
            type: object
            properties:
              status:
                type: string
                description: ENUM 'Success'
                default: Success
              count:
                type: integer
                description: Number of records being returned
                
              measure:
                type: array
                items:
                  - $ref: '#/definitions/food_waste'
        404:
          description: Requested resource does not exist.
        405:
          description: HTTP Verb / Operation not supported
definitions:
  food_waste:
    type: object
    properties:
      fiscal_period:
        type: string
        description: Fiscal Month of data
      fiscal_week_no:
        type: integer
        description: Fiscal Week of Month
      fiscal_day:
        type: integer
        description: Fiscal Day of Week
      fiscal_day_id:
        type: integer
        description: Fiscal Day ID
      org_value:
        type: string
        description: Aramark Organization code for rollup
      org_name:
        type: string
        description: Name or Aramark Organization rollup
      waste_currency:
        type: number
        description: Waste Dollars
      waste_weight:
        type: number
        description: Waste Weight
      waste_days_compliant:
        type: number
        description: Number of Days Waste was reported
      waste_days_required:
        type: number
        description: Number of Days Waste was expected to be reported
