openapi: 3.0.0
info:
  description: This API will return data related to different Growth metrics
  version: "1.0.0-oas3"
  title: Growth
tags:
  - name: PVI
    description: Partner Value Index
paths:
  '/pvi/score/{org_value}':
    get:
      description: Returns PVI Score for a specific organization
      operationId: getPVIScore
      tags:
        - PVI
      parameters:
        - in: path
          name: org_value
          description: Aramark Organization code for rollup
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/startPeriodParam'
        - $ref: '#/components/parameters/endPeriodParam'
        - $ref: '#/components/parameters/rollupParam'
        - $ref: '#/components/parameters/bypassCacheParam'
        - $ref: '#/components/parameters/smokeParam'
      responses:
        '200':
          description: Provides the service results for a specific unit of measure
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: 'ENUM ''Success'', ''Error'' or ''Not Found'''
                    default: Success
                    example: Success
                  count:
                    type: string
                    description: Number of records returned
                    default: '0'
                    example: '1'
                  pvi_scores:
                    type: array
                    items:
                      $ref: '#/components/schemas/pvi_scores'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
  '/pvi/score/client/{client_value}':
    get:
      description: Returns PVI Score for a specific client
      operationId: getPVIScoreByClient
      tags:
        - PVI
      parameters:
        - in: path
          name: client_value
          description: Aramark Client code
          required: true
          schema:
            type: string
            default: 'Y'
        - $ref: '#/components/parameters/startPeriodParam'
        - $ref: '#/components/parameters/endPeriodParam'
        - $ref: '#/components/parameters/rollupParam'
        - in: query
          name: sort
          description: >-
            This flag will sort multiple fiscal periods either Ascending or
            Descending
          required: false
          schema:
            type: string
            enum:
              - ASC
              - DESC
            default: ASC
        - $ref: '#/components/parameters/bypassCacheParam'
        - $ref: '#/components/parameters/smokeParam'
      responses:
        '200':
          description: Provides the service results for a specific unit of measure
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: 'ENUM ''Success'', ''Error'' or ''Not Found'''
                    default: Success
                    example: Success
                  count:
                    type: string
                    description: Number of records returned
                    default: '0'
                    example: '1'
                  pvi_scores:
                    type: array
                    items:
                      $ref: '#/components/schemas/client_pvi_scores'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
servers:
  - url: https://{environment}.aramark.net/v1/growth
    variables:
      environment:
        description: >-
          Server choices:
           * `qa-marko` QA server, is the default.
           * `dev-marko` Development server.**
        default: qa-marko
        enum:
          - dev-marko
          - qa-marko
components:
  parameters:
    startPeriodParam:
      in: query
      name: start_period
      description: Starting fiscal period. "MON_FY-YY"
      required: true
      schema:
        type: string
    endPeriodParam:
      in: query
      name: end_period
      description: Ending fiscal period. Will use start_period if not provided. "MON_FY-YY"
      required: false
      schema:
        type: string
    rollupParam:
      in: query
      name: rollup
      description: >-
        Flag used to determine whether or not output will display an aggregate
        of child organizations or not.
      required: false
      schema:
        type: string
        enum:
          - 'Y'
          - 'N'
        default: 'Y'
    bypassCacheParam:
      in: header
      name: bypass-cache
      description: This HTTP Header variable will bypass cache.
      schema:
        type: string
        enum:
          - 'true'
          - 'false'
        default: 'false'
    smokeParam:
      in: header
      name: smoke
      description: >-
        When set to 'true' this HTTP header variable will route the API call to
        the Integration testing environment.  Only applicable in QA.
      schema:
        type: string
        default: false
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: apikey
      description: This HTTP Header variable will verify permissions.
  schemas:
    pvi_scores:
      type: object
      properties:
        fiscal_period:
          type: string
          description: Aramark fiscal period
          example: SEP_FY-18
        org_value:
          type: string
          description: Aramark Organization code for rollup
          example: 99FSS0000
        org_name:
          type: string
          description: Name or Aramark Organization rollup
          example: ARAMARK Domestic Food & Support Services
        pvi_score:
          type: number
          description: Partner Value Index score for given fiscal period
          example: 75.9
        target_pvi_score:
          type: number
          description: Target PVI Score for given fiscal period
          example: 80
        py_target_pvi_score:
          type: number
          description: Prior Year Target PVI Score for given fiscal period
          example: 82
    client_pvi_scores:
      type: object
      properties:
        fiscal_period:
          type: string
          description: Aramark fiscal period
          example: SEP_FY-18
        client_value:
          type: string
          description: Aramark Organization code for rollup
          example: 99FSS0000
        client_name:
          type: string
          description: Name or Aramark Organization rollup
          example: ARAMARK Domestic Food & Support Services
        pvi_score:
          type: number
          description: Partner Value Index score for given fiscal period
          example: 75.9
        target_pvi_score:
          type: number
          description: Target PVI Score for given fiscal period
          example: 80
        py_target_pvi_score:
          type: number
          description: Prior Year Target PVI Score for given fiscal period
          example: 82
