openapi: 3.0.0
info:
  summary: Growth metrics
  description: |
    This API will return data related to different Growth metrics

    __The base endpoint URL for this API in production is:__ `https://marko.aramark.net/v1/growth`.
  version: "1.0.0-oas3"
  title: Growth
tags:
  - name: VOC
    description: Voice of the Consumer Survey Results
paths:
  '/voc/results/{org_value}':
    get:
      summary: Voice of Consumer survey
      description: |
        Returns Voice of the Consumer Survey Results for a specific Location

        ![This endpoint is in QA](/themes/portal/images/statuspngs/statusqa.png)
      operationId: getVOCResults
      tags:
        - VOC
      parameters:
        - $ref: '#/components/parameters/orgValueParam'
        - $ref: '#/components/parameters/startDateParam'
        - $ref: '#/components/parameters/endDateParam'
        - $ref: '#/components/parameters/surveyTypeParam'
        - $ref: '#/components/parameters/surveyGroupParam'
        - $ref: '#/components/parameters/pageParam'
        - $ref: '#/components/parameters/sizeParam'
        - $ref: '#/components/parameters/bypassCacheParam'
        - $ref: '#/components/parameters/smokeParam'
      responses:
        '200':
          description: Provides the service results for a specific unit of measure
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: 'ENUM ''Success'', ''Error'' or ''Not Found'''
                    default: Success
                    example: Success
                  count:
                    type: string
                    description: Number of records returned
                    default: '0'
                    example: '1'
                  survey_response:
                    type: array
                    items:
                      $ref: '#/components/schemas/survey_response'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
servers:
  - url: https://qa-marko.aramark.net/v1/growth
    description: Testing server
  - url: https://dev-marko.aramark.net/v1/growth
    description: Development server
components:
  parameters:
    orgValueParam:
      in: path
      name: org_value
      description: Aramark Location code for rollup
      required: true
      schema:
        type: string
    startDateParam:
      in: query
      name: start_date
      description: Calendar date for responses. "mm/dd/yyyy"
      required: true
      schema:
        type: string
    endDateParam:
      in: query
      name: end_date
      description: >-
        Calendar date end date for responses. Will use start_date if not
        provided. "mm/dd/yyyy"
      schema:
        type: string
    surveyTypeParam:
      name: survey_type
      in: query
      description: >-
        Comma separated list of codes to determine which type of survey questions to return. 
          - "HLTH" - Health 
          - "PERS" - Personalization
          - "QUAL" - Quality
          - "SAT" - Satisfaction
          - "ALL" - All Types
      required: false
      schema:
        type: string
        default: ALL
    surveyGroupParam:
      name: survey_group
      in: query
      description: >-
        Comma separated list of codes to determine which survey group to return.
          - "CATERING" - Catering
          - "DINING" - Dining
          - "ALL" - All Groups
      required: false
      schema:
        type: string
        default: ALL
    pageParam:
      in: query
      name: page
      description: Page number of result set
      required: false
      schema:
        type: number
        default: 1
    sizeParam:
      in: query
      name: size
      description: Number of rows in each page to return.
      required: false
      schema:
        type: string
        default: 50
    bypassCacheParam:
      in: header
      name: bypass-cache
      description: This HTTP Header variable will bypass cache.
      schema:
        type: string
        enum:
          - 'true'
          - 'false'
        default: 'false'
    smokeParam:
      in: header
      name: smoke
      description: >-
        When set to 'true' this HTTP header variable will route the API call to
        the Integration testing environment.  Only applicable in QA.
      schema:
        type: string
        default: false
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: apikey
      description: This HTTP Header variable will verify permissions.
  schemas:
    survey_response:
      type: object
      properties:
        profit_center:
          type: string
          description: Aramark Profit Center value
        profit_center_name:
          type: string
          description: Aramark Profit Center Name
        location:
          type: string
          description: Aramark Location value
        location_name:
          type: string
          description: Aramark Location Name
        survey_group:
          type: string
          description: Description of the group the survey
        survey_type:
          type: string
          description: Description of the type of survey question
        measure_value:
          type: string
          description: Value of the survey response
        response_date:
          type: string
          description: Calendar date of the survey response
        country:
          type: string
          description: Coutnry code of the response
