openapi: 3.0.0
info:
  description: |

    This is a collection of APIs to support GSC GPO

    The base endpoint URL for this API in production is: `https://marko.aramark.net/i1/gsc_gpo`.

    For testing the API with the "Try" tool on this page or in your app, use either our testing server "qa-marko" or our development server "dev-marko".
  version: 1.0.0-oas3
  title: GSC GPO
security:
  - apiKey: []
paths:
# this is what comes after the base path.
  /security/avendra:
    get:
      operationId: getAvendraSecurity
      tags:
        - Security
      summary: Gets Avendra User Security Data
      parameters:
        - $ref: '#/components/parameters/userIdParam'
        - $ref: '#/components/parameters/bypassCacheParam'
      responses:
        '200':
          description: Collection of Avendra User Security Data
          content:
            '*/*':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ENUM 'Success' or 'Error'
                    default: Success
                  count:
                    type: number
                    description: Number of records returned
                  avendra_security:
                    type: array
                    items:
                      $ref: '#/components/schemas/avendra_security'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
  /spend/bracket/client:
    get:
      operationId: getClientBracketSpend
      tags:
        - Spend
      summary: Gets Client Bracket Spend Data
      parameters:
        - $ref: '#/components/parameters/clientIdParam'
        - $ref: '#/components/parameters/bypassCacheParam'
      responses:
        '200':
          description: Collection of Bracket Client Spend Data
          content:
            '*/*':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ENUM 'Success' or 'Error'
                    default: Success
                  count:
                    type: number
                    description: Number of records returned
                  client_bracket:
                    type: array
                    items:
                      $ref: '#/components/schemas/client_bracket'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
  /spend/impact/client:
    get:
      operationId: getClientImpactSpend
      tags:
        - Spend
      summary: Gets Client Impact Spend Data
      parameters:
        - $ref: '#/components/parameters/clientIdParam'
        - $ref: '#/components/parameters/bypassCacheParam'
      responses:
        '200':
          description: Collection of Impact Client Spend Data
          content:
            '*/*':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ENUM 'Success' or 'Error'
                    default: Success
                  count:
                    type: number
                    description: Number of records returned
                  client_impact:
                    type: array
                    items:
                      $ref: '#/components/schemas/client_impact'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
  /spend/po/client:
    get:
      operationId: getClientPOSpend
      tags:
        - Spend
      summary: Gets Client PO Spend Data
      parameters:
        - $ref: '#/components/parameters/clientIdParam'
        - $ref: '#/components/parameters/bypassCacheParam'
      responses:
        '200':
          description: Collection of PO Client Spend Data
          content:
            '*/*':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ENUM 'Success' or 'Error'
                    default: Success
                  count:
                    type: number
                    description: Number of records returned
                  client_po:
                    type: array
                    items:
                      $ref: '#/components/schemas/client_po'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
  /spend/yoy/client:
    get:
      operationId: getClientYOYSpend
      tags:
        - Spend
      summary: Gets Client YOY Spend Data
      parameters:
        - $ref: '#/components/parameters/clientIdParam'
        - $ref: '#/components/parameters/bypassCacheParam'
      responses:
        '200':
          description: Collection of YOY Client Spend Data
          content:
            '*/*':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ENUM 'Success' or 'Error'
                    default: Success
                  count:
                    type: number
                    description: Number of records returned
                  yoy_spend:
                    type: array
                    items:
                      $ref: '#/components/schemas/yoy_spend'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
  /spend/top_customer_spend:
    get:
      operationId: getCustomerSpend
      tags:
        - Spend
      summary: Gets Client Customer Spend Data
      parameters:
        - $ref: '#/components/parameters/clientIdParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/bypassCacheParam'
      responses:
        '200':
          description: Collection of Customer Spend Data
          content:
            '*/*':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ENUM 'Success' or 'Error'
                    default: Success
                  count:
                    type: number
                    description: Number of records returned
                  top_customers:
                    type: array
                    items:
                      $ref: '#/components/schemas/top_customers'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
  /spend/top_manufacturer_spend:
    get:
      operationId: getManufacturerSpend
      tags:
        - Spend
      summary: Gets Client Manufacturer Spend Data
      parameters:
        - $ref: '#/components/parameters/clientIdParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/bypassCacheParam'
      responses:
        '200':
          description: Collection of Manufacturer Spend Data
          content:
            '*/*':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ENUM 'Success' or 'Error'
                    default: Success
                  count:
                    type: number
                    description: Number of records returned
                  top_manufacturers:
                    type: array
                    items:
                      $ref: '#/components/schemas/top_manufacturers'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
  /spend/top_distributor_spend:
    get:
      operationId: getDistributorSpend
      tags:
        - Spend
      summary: Gets Client Distributor Spend Data
      parameters:
        - $ref: '#/components/parameters/clientIdParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/bypassCacheParam'
      responses:
        '200':
          description: Collection of Distributor Spend Data
          content:
            '*/*':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ENUM 'Success' or 'Error'
                    default: Success
                  count:
                    type: number
                    description: Number of records returned
                  top_distributors:
                    type: array
                    items:
                      $ref: '#/components/schemas/top_distributors'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
  /spend/ipo:
    get:
      operationId: getIPODdata
      tags:
        - Spend
      summary: Gets Client IPO Data
      parameters:
        - $ref: '#/components/parameters/clientIdParam'
        - $ref: '#/components/parameters/bypassCacheParam'
      responses:
        '200':
          description: Collection of IPO Spend Data
          content:
            '*/*':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ENUM 'Success' or 'Error'
                    default: Success
                  count:
                    type: number
                    description: Number of records returned
                  ipo_data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ipo_data'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
  /spend/category/client:
    get:
      operationId: getCategorySpend
      tags:
        - Spend
      summary: Gets Client Category Spend Data
      parameters:
        - $ref: '#/components/parameters/clientIdParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/bypassCacheParam'
      responses:
        '200':
          description: Collection of Category Spend Data
          content:
            '*/*':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ENUM 'Success' or 'Error'
                    default: Success
                  count:
                    type: number
                    description: Number of records returned
                  category_spend:
                    type: array
                    items:
                      $ref: '#/components/schemas/category_spend'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
servers:
# If spec is only in dev, then delete the "Testing Server"
  - url: https://qa-marko.aramark.net/i1/gsc_gpo
    description: Testing server
  - url: https://dev-marko.aramark.net/i1/gsc_gpo
    description: Development server
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: apikey
      description: This HTTP Header variable will verify permissions.
  parameters:
    clientIdParam:
      in: query
      name: client_id
      description: User ID, customerKey or parentID of the client
      required: true
      schema:
        type: string
    userIdParam:
      in: query
      name: user_id
      description: User ID of the customer
      required: true
      schema:
        type: string
    pageParam:
      in: query
      name: page
      description: Page number of result set
      schema:
        type: number
        default: 1
    limitParam:
      in: query
      name: limit
      description: Number of ranked records to return
      schema:
        type: number
        default: 5
    sizeParam:
      in: query
      name: size
      description: Number of records to be returned in each page of result set
      schema:
        type: string
        default: 50
    bypassCacheParam:
      in: header
      name: bypass-cache
      description: This HTTP Header variable will bypass cache.
      schema:
        type: string
        enum:
          - 'true'
          - 'false'
        default: 'false'
  schemas:
    yoy_spend:
      type: object
      properties:
        yoy_change:
          type: number
        current_year_spend:
          type: number
        current_year_start:
          type: string
        current_year_end:
          type: string
        prior_year_spend:
          type: number
        prior_year_start:
          type: string
        prior_year_end:
          type: string
    top_customers:
      type: object
      properties:
        customer_name:
          type: string
        customer_key:
          type: number
        spend:
          type: number
    top_manufacturers:
      type: object
      properties:
        manufacturer_name:
          type: string
        spend:
          type: number
    top_distributors:
      type: object
      properties:
        distributors_name:
          type: string
        spend:
          type: number
    ipo_data:
      type: object
      properties:
        customer_count:
          type: number
        item_count:
          type: number
        spend:
          type: number
    avendra_security:
      type: object
      properties:
        customer_key:
          type: number
        customer_name:
          type: string
        customer_id:
          type: string
        customer_parent_id:
          type: string
        customer_parent_name:
          type: string
        customer_parent_key:
          type: number
    client_bracket:
      type: object
      properties:
        distributor_warehouse_name:
          type: string
        current_bracket:
          type: string
        trending_bracket:
          type: string
        target_bracket:
          type: string
        mfd_spend:
          type: number
        delivery_count:
          type: number
        average_delivery_size:
          type: number
        bracket_evaluation_start_date:
          type: string
        bracket_evaluation_end_date:
          type: string
    client_impact:
      type: object
      properties:
        distributor_warehouse_name:
          type: string
        contracted_spend_percent:
          type: number
        non_contracted_spend_percent:
          type: number
        contracted_spend_percent_prior_month:
          type: number
        contracted_spend_percent_prior_year:
          type: number
    client_po:
      type: object
      properties:
        opportunity:
          type: number
        estimated_participation:
          type: number
        actual_spend:
          type: number
        potential_spend:
          type: number
        yoy_growth:
          type: number
    category_spend:
      type: object
      properties:
        category_name:
          type: string
        spend:
          type: number