openapi: 3.0.0
info:
  description: | 

    This API will return Employee information

    The base endpoint URL for this API in production is: `https://marko.aramark.net/v1/labor/employee`.

    For testing the API with the "Try" tool on this page or in your app, use either our testing server "qa-marko" or our development server "dev-marko".
  version: "1.0.0-oas3"
  title: Labor Employee
tags:
  - name: Accruals
    description: Get Employee Scheduled Shifts
  - name: Manager
    description: Get Manager information for an Employee
paths:
  /accrual:
    # proxy name: Labor-Employee-Accruals-API
    get:
      summary: Accrual balance for employee
      description: |

        Returns a collection of accrual balance information for an employee.

        ![This endpoint is in prod](/themes/portal/images/statuspngs/statusprod.png)
      operationId: getEmployeeAccrual
      tags:
        - Accruals
      parameters:
        - $ref: '#/components/parameters/employeeIdParam'
        - $ref: '#/components/parameters/effectiveDateParam'
        - $ref: '#/components/parameters/bypassCacheParam'
        - $ref: '#/components/parameters/smokeParam'
      responses:
        '200':
          description: Provides the accrual balance data
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: 'ENUM ''Success'', ''Error'' or ''Not Found'''
                    default: Success
                  count:
                    type: integer
                    description: Number of records being returned
                  accrual_balances:
                    type: array
                    items:
                      $ref: '#/components/schemas/accrual_balances'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
  /manager:
    # proxy name: Labor-Employee-Supervisor-API
    # proxy display name: Labor-Employee-Manager-API
    get:
      description: |
        
        Returns a manager id of employee.

        ![This endpoint is in prod](/themes/portal/images/statuspngs/statusprod.png)
      operationId: getEmployeeManager
      # proxy name: Labor-Employee-Supervisor-API
      # proxy display name: Labor-Employee-Manager-API
      tags:
        - Manager
      parameters:
        - $ref: '#/components/parameters/employeeIdParam'
        - $ref: '#/components/parameters/bypassCacheParam'
        - $ref: '#/components/parameters/smokeParam'
      responses:
        '200':
          description: Provides the Supervisor data for an employee
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: 'ENUM ''Success'', ''Error'' or ''Not Found'''
                    default: Success
                  count:
                    type: integer
                    description: Number of records being returned
                  manager:
                    type: array
                    items:
                      $ref: '#/components/schemas/manager'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
servers:
  - url: 'https://qa-marko.aramark.net/v1/labor/employee'
  - url: 'https://dev-marko.aramark.net/v1/labor/employee'
components:
  parameters:
    employeeIdParam:
      in: query
      name: employee_id
      description: Unique identifier of the employee
      required: true
      schema:
        type: string
    effectiveDateParam:
      in: query
      name: effective_date
      description: Calendar date for which the accrual balance is effective "MM/DD/YYYY"
      required: true
      schema:
        type: string
    bypassCacheParam:
      in: header
      name: bypass-cache
      description: This HTTP Header variable will bypass cache
      schema:
        type: string
        enum:
          - 'true'
          - 'false'
        default: 'false'
    smokeParam:
      in: header
      name: smoke
      description: >-
        When set to 'true' this HTTP Header variable will route to the
        Integration environment.  Only applicable in QA Server
      schema:
        type: string
        enum:
          - 'true'
          - 'false'
        default: 'false'
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: apikey
      description: This HTTP Header variable will verify permissions.
  schemas:
    accrual_balances:
      type: object
      properties:
        employee_id:
          type: string
          description: Unique ID for the employee
        employee_name:
          type: string
          description: First and Last name of the employee
        accrual_code:
          type: string
          description: Unique code to describe the type of accrual balance
        accrual_balance:
          type: string
          description: Actual amount of the accrual for the employee
    manager:
      type: object
      properties:
        manager_id:
          type: string
          description: Unqiue ID for the employee's manager
