# All text in "< >" should be replaced with actual values. Remove the < >.
openapi: 3.0.0
info:
  description: |

    Returns info about the NFL Schedule 

  The base endpoint URL for this API in production is: `https://profootballapi.com`.

  version: 1.0.0-oas3
  title: NFL Football Schedule
security:
  - apiKey: []
paths:
# this is what comes after the base path.
  /schedule:
    get:
      operationId: getNflSchedule
      summary: Returns list of NFL games
      description: |
        
        Return a list of NFL games based on a variety of parameters set in the query. 
        # Delete two of the following three lines. Endpoint can have only one state.
        ![This endpoint is in production](/themes/portal/images/statuspngs/statusprod.png)
      parameters:
      # Some sample parameters including common ones at top
      # Delete the ones you are not using
        - $ref: '#/components/parameters/yearParam'
        - $ref: '#/components/parameters/monthParam'
        - $ref: '#/components/parameters/dayParam'
        - $ref: '#/components/parameters/timeParam'
        - $ref: '#/components/parameters/seasonTypeParam'
        - $ref: '#/components/parameters/weekParam'

      responses:
        '200':
          description: NFL schedule detail
          content:
            '*/*':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ENUM 'Success' or 'Error'
                    default: Success
                  count:
                    type: string
                    description: Number of games that meet parameter
                  nfl_games:
                    type: array
                    items:
                      $ref: '#/components/schemas/nfl_games'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
servers:
# If spec is only in dev, then delete the "Testing Server"
  - url: https://profootballapi.com/schedule
    description: Production server
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: apikey
      description: This HTTP Header variable will verify permissions.
  parameters:
    yearParam:
      in: query
      name: year
      description: The year of the season that you would like to find the schedule for. 
      required: false
      schema:
        type: number
    monthParam:
      in: query
      name: month
      description: The month of the season that you would like to find the schedule for.
      required: false
      schema:
        type: number
    dayParam:
      in: query
      name: day
      description: The day of the month of the season that you would like to find the schedule for. 
      required: false
      schema:
        type: number
    timeParam:
      in: query
      name: time
      description: The unix time of kickoff for games of the season that you would like to find the schedule for.
      required: false
      schema:
        type: number
    seasonTypeParam:
      in: query
      name: season_type
      description: Enum values for pre-season, regular season, and post season.
      schema:
        type: string
        enum:
          - 'PRE'
          - 'REG'
          - 'POST'
  schemas:
    nfl_games:
      type: object
      properties:
        year:
          type: number
          description: The year of the season that you would like to find the schedule for. 
        month:
          type: number
          description: The month of the season that you would like to find the schedule for.
        day:
          type: number
          description: The day of the month of the season that you would like to find the schedule for. 
        time:
          type: number
          description: The unix time of kickoff for games of the season that you would like to find the schedule for.
        season_type:
          type: string
          description: Enum values (`PRE`, `REG`, `POST`) for pre-season, regular season, and post season.

