openapi: 3.0.0
info:
  description: |

    This API will return a collection of Service Production Departments by Production Area


    The base endpoint URL for this API in production is: `https://marko.aramark.net/v1/service`.

    For testing the API with the "Try" tool on this page or in your app, use either our testing server "qa-marko" or our development server "dev-marko".
  version: 1.0.0-oas3
  title: Service Production Departments
tags:
  - name: Production Departments
    description: Service Production Departments by Production Area
security:
  - apiKey: []
paths:
  /production_departments:
    get:
      summary: Returns production department from service area
      description: |

        Returns Service Production Departments with a given Production Area ID

        ![This endpoint is in development](/themes/portal/images/statuspngs/statusdev.png)
      operationId: getServiceProductionDepartments
      tags:
        - Production Departments
      parameters:
        - $ref: '#/components/parameters/siteIdParam'
        - $ref: '#/components/parameters/bypassCacheParam'
        - $ref: '#/components/parameters/smokeParam'
      responses:
        '200':
          description: List all Production Departments for a Production Area
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: 'ENUM ''Success'', ''Error'' or ''Not Found'''
                  count:
                    type: string
                    description: Number of records returned in request
                  production_departments:
                    type: array
                    items:
                      $ref: '#/components/schemas/production_departments'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
servers:
  - url: https://dev-marko.aramark.net/v1/service
    description: Development server
  - url: https://qa-marko.aramark.net/v1/service
    description: Testing server
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: apikey
      description: This HTTP Header variable will verify permissions.
  parameters:
    siteIdParam:
      name: site_id
      in: query
      description: Unique ID of Site
      required: true
      schema:
        type: string
    bypassCacheParam:
      in: header
      name: bypass-cache
      description: This HTTP Header variable will bypass cache.
      schema:
        type: string
        enum:
          - 'true'
          - 'false'
        default: 'false'
    smokeParam:
      in: header
      name: smoke
      description: When set to 'true' this HTTP header variable will route the API call to the Integration testing environment. Only applicable in QA.
      schema:
        type: string
        default: 'false'
  schemas:
    production_departments:
      type: object
      properties:
        site_id:
          type: number
          description: unique identifier of a site
        site_name:
          type: string
          description: name of a site
        profit_center:
          type: string
          description: organization code of the profit center
        profit_center_name:
          type: string
          description: name of the profit center
        location_id:
          type: number
          description: unique identifier of a location
        location_name:
          type: string
          description: name of a location
        service_area_id:
          type: number
          description: Unique code for a Service Area, sourced by PRIMA and kept for backwards compatibility, will be DEPRECATED
        service_area_name:
          type: string
          description: Service Area descriptive name
        production_area_id:
          type: number
          description: unique identifier of a prouction area
        production_area_name:
          type: string
          description: name of a production area
        production_department_id:
          type: number
          description: unique identifier of a production department
        production_department_name:
          type: string
          description: name of a production department
