openapi: 3.0.0
info:
  description: |
    This API will return a collection of Service Recipes for Menu Items and the nutrition data for a specific Location, Service Date and Meal Period.

    The base endpoint URL for this API in production is: `https://marko.aramark.net/v1/service`.
    
    For testing the API with the "Try" tool on this page or in your app, use either our testing server "qa-marko" or our development server "dev-marko".
  version: "1.0.0-oas3"
  title: Service Recipe
tags:
  - name: Service Recipes
    description: | 
      An individual Service Recipe and its Ingredients for a Location, Service Date, Service Area and Meal Period
paths:
  /recipes:
    get:
      summary: Recipes and ingredients
      description: | 

        Returns a Hierarchal collection of Service Recipes and Ingredients for a Service Menu. This interfaces requires either service_area_id or sub_location_id to be provided.

        ![This endpoint is in production](/themes/portal/images/statuspngs/statusprod.png)
      operationId: getServiceRecipes
      tags:
        - Service Recipes
      parameters:
        - $ref: '#/components/parameters/serviceDateParam'
        - $ref: '#/components/parameters/serviceAreaIdParam'
        - $ref: '#/components/parameters/subLocationIdParam'
        - $ref: '#/components/parameters/mealPeriodIdParam'
        - $ref: '#/components/parameters/bypassCacheParam'
        - $ref: '#/components/parameters/smokeParam'
        - name: bypass-cache
          in: header
          description: This HTTP Header variable will bypass cache
          schema:
            type: string
            enum:
              - 'true'
              - 'false'
            default: false
        - name: smoke
          in: header
          description: >-
            When set to 'true' this HTTP header variable will route the API call
            to the Integration testing environment.  Only applicable in QA.
          schema:
            type: string
            default: false
      responses:
        '200':
          description: 'List all Menu Items for Location, Service Data and Meal Period.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: 'ENUM ''Success'', ''Error'' or ''Not Found'''
                  count:
                    type: string
                    description: Number of records returned in request
                  service_recipes:
                    type: array
                    items:
                      $ref: '#/components/schemas/service_recipes'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
servers:
  - url: https://qa-marko.aramark.net/v1/service
    description: Testing server
  - url: https://dev-marko.aramark.net/v1/service
    description: Development server
components:
  parameters:
    serviceDateParam:
      name: service_date
      in: query
      description: Service Date in Format "mm/dd/yyyy"
      required: true
      schema:
        type: string
    serviceAreaIdParam:
      name: service_area_id
      in: query
      description: >-
        Unique ID of Service Area for a Service Date.  Either
        service_area_id or sub_location_id are REQUIRED.
      required: false
      schema:
        type: string
    subLocationIdParam:
      name: sub_location_id
      in: query
      description: >-
        Unique ID of Sub Location aka Station for a Service Date. Either
        service_area_id or sub_location_id are REQUIRED.
      required: false
      schema:
        type: string
    mealPeriodIdParam:
      name: meal_period_id
      in: query
      description: Unique ID of Meal Period for a Location and Service Date.
      required: false
      schema:
        type: string
      in: header
    bypassCacheParam:
      name: bypass-cache
      description: This HTTP Header variable will bypass cache
      schema:
        type: string
        enum:
          - 'true'
          - 'false'
    smokeParam:
      in: header
      name: smoke
      description: |
        When set to 'true' this HTTP Header variable will route to the Integration environment.  Only applicable in QA Server.
      schema:
        type: string
        enum:
          - 'true'
          - 'false'
  securitySchemes:
    apikey:
      type: apiKey
      in: header
      name: apikey
      description: This HTTP Header variable will verify security
  schemas:
    service_recipes:
      type: object
      properties:
        recipe:
          type: array
          items:
            $ref: '#/components/schemas/recipes'
    recipes:
      type: object
      properties:
        service_area_id:
          type: integer
          description: >-
            Unique code for a Service Area, sourced by PRIMA and kept for
            backwards compatibility, will be DEPRECATED
        service_area_name:
          type: string
          description: Service Area descriptive name
        service_date:
          type: string
          description: Calendar date of service in 'MM/DD/YYYY' format
        meal_period_id:
          type: integer
          description: Unique ID of Meal period
        meal_period:
          type: string
          description: Descriptive name of service meal period
        sub_location_id:
          type: integer
          description: 'Unique code for a Sub Location, sourced by PRIMA or MDG'
        sub_location_name:
          type: string
          description: Sub Location descriptive name
        recipe_id:
          type: string
          description: PRIMA Recipe ID
        recipe_name:
          type: string
          description: PRIMA Recipe name of Menu Items
        serving_size_display:
          type: string
          description: Serving Size Description
        uom_system:
          type: string
          description: What Unit of measurement system is being used
        special_instructions:
          type: string
          description: Special Instructions
        assembly_instructions:
          type: string
          description: Assembly Instructions
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/ingredients'
    ingredients:
      type: object
      properties:
        ingredient_id:
          type: string
          description: PRIMA Recipe Ingredient ID
        ingredient_name:
          type: string
          description: PRIMA Recipe Ingredient Name
        unit_of_measure_id:
          type: string
          description: Unit of measure type ID
        unit_of_measure:
          type: string
          description: Unit of measure description
        amount_needed:
          type: number
          description: Ingredient amount per serving
        prep_tech:
          type: string
          description: Preparation Technique (Nullable)
        prep_method:
          type: string
          description: Preparation Method (Nullable)
        sub_assembly_id:
          type: string
          description: PRIMA Recipe ID if Ingredient is a sub-assembly (Nullable)
        is_lb_threshold:
          type: string
          description: Y/N is ingredient lb threshold
        ozw_per_tsp:
          type: string
          description: Decimal factor used for conversion of Once Weight (Nullable)
