# All text in "< >" should be replaced with actual values. Remove the < >.
openapi: 3.0.0
info:
  description: |

    <Describe API here.>

    The base endpoint URL for this API in production is: `https://marko.aramark.net/v1/<base_path>`.

    For testing the API with the "Try" tool on this page or in your app, use either our testing server "qa-marko" or our development server "dev-marko".
  version: 1.0.0-oas3
  title: <API Title>
security:
  - apiKey: []
paths:
# this is what comes after the base path.
  /path/to/endpoint/{<path_parameter>}:
    get:
      operationId: <getExampleData>
      summary: <brief description of method>
      description: |
        <multiline description of API method. Can include markdown>
        # Delete two of the following three lines. Endpoint can have only one state.
        ![This endpoint is in production](/themes/portal/images/statuspngs/statusprod.png)
        ![This endpoint is in qa testing](/themes/portal/images/statuspngs/statusqa.png)
        ![This endpoint is in development](/themes/portal/images/statuspngs/statusdev.png)
      parameters:
      # Some sample parameters including common ones at top
      # Delete the ones you are not using
        - $ref: '#/components/parameters/pageParam'
        - $ref: '#/components/parameters/sizeParam'
        - $ref: '#/components/parameters/bypassCacheParam'
        - $ref: '#/components/parameters/smokeParam'
        - $ref: '#/components/parameters/accountParam'
        - $ref: '#/components/parameters/barcodeParam'
        - $ref: '#/components/parameters/cpgParam'
        - $ref: '#/components/parameters/dateOfBirthParam'
        - $ref: '#/components/parameters/deviceIdParamFalse'
        - $ref: '#/components/parameters/deviceIdParamTrue'
        - $ref: '#/components/parameters/effectiveDateParam'
        - $ref: '#/components/parameters/emailParam'
        - $ref: '#/components/parameters/employeeEmailParam'
        - $ref: '#/components/parameters/employeeIdParam'
        - $ref: '#/components/parameters/employeeIdParamNotRequired'
        - $ref: '#/components/parameters/enabledParam'
        - $ref: '#/components/parameters/endDateParam'
        - $ref: '#/components/parameters/endDateTimeParam'
        - $ref: '#/components/parameters/fieldsParam'

      responses:
        '200':
          description: <description of output>
          content:
            '*/*':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ENUM 'Success' or 'Error'
                    default: Success
                  count:
                    type: string
                    description: Number of calendar dates returned
                  <output_schema_name>:
                    type: array
                    items:
                      $ref: '#/components/schemas/<output_schema_name>'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
  /path/to/another/endpoint/{<path_parameter>}:
    get:
      operationId: <getExampleData22>
      summary: <brief description of method>
      description: |
        <multiline description of API method. Can include markdown>
        # Delete two of the following three lines. Endpoint can have only one state.
        ![This endpoint is in production](/themes/portal/images/statuspngs/statusprod.png)
        ![This endpoint is in qa testing](/themes/portal/images/statuspngs/statusqa.png)
        ![This endpoint is in development](/themes/portal/images/statuspngs/statusdev.png)
      parameters:
      # Some sample parameters including common ones at top
      # Delete the ones you are not using
        - $ref: '#/components/parameters/pageParam'
        - $ref: '#/components/parameters/sizeParam'
        - $ref: '#/components/parameters/bypassCacheParam'
        - $ref: '#/components/parameters/smokeParam'
        - $ref: '#/components/parameters/accountParam'
        - $ref: '#/components/parameters/barcodeParam'
        - $ref: '#/components/parameters/cpgParam'
        - $ref: '#/components/parameters/dateOfBirthParam'
        - $ref: '#/components/parameters/deviceIdParamFalse'
        - $ref: '#/components/parameters/deviceIdParamTrue'
        - $ref: '#/components/parameters/effectiveDateParam'
        - $ref: '#/components/parameters/emailParam'
        - $ref: '#/components/parameters/employeeEmailParam'
        - $ref: '#/components/parameters/employeeIdParam'
        - $ref: '#/components/parameters/employeeIdParamNotRequired'
        - $ref: '#/components/parameters/enabledParam'
        - $ref: '#/components/parameters/endDateParam'
        - $ref: '#/components/parameters/endDateTimeParam'
        - $ref: '#/components/parameters/fieldsParam'

      responses:
        '200':
          description: <description of output>
          content:
            '*/*':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: ENUM 'Success' or 'Error'
                    default: Success
                  count:
                    type: string
                    description: Number of calendar dates returned
                  <output_schema_name>:
                    type: array
                    items:
                      $ref: '#/components/schemas/<output_schema_2_name>'
        '404':
          description: Requested resource does not exist.
        '405':
          description: HTTP Verb / Operation not supported
servers:
# If spec is only in dev, then delete the "Testing Server"
  - url: https://qa-marko.aramark.net/v1/<base_path>
    description: Testing server
  - url: https://dev-marko.aramark.net/v1/<base_path>
    description: Development server
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: apikey
      description: This HTTP Header variable will verify permissions.
  parameters:
    userIdParam:
      in: query
      name: user_id
      description: Email address of the manager
      required: true
      schema:
        type: string
    orgValueParam:
      in: path
      name: org_value
      description: provide business organization code in URL to filter data set
      required: true
      schema:
        type: string
    startDateParam:
      in: query
      name: start_date
      description: Calendar date for daily transactions. "mm/dd/yyyy"
      required: false
      schema:
        type: string
    endDateParam:
      in: query
      name: end_date
      description: >-
        Calendar date end date for daily transactions. Will use start_date if
        not provided. "mm/dd/yyyy"
      required: false
      schema:
        type: string
    pageParam:
      in: query
      name: page
      escription: Page number of result set
      required: false
      schema:
        type: number
        default: 1
    sizeParam:
      name: size
      in: query
      description: Number of records to be returned in each page of result set
      schema:
        type: string
        default: 50
    bypassCacheParam:
      in: header
      name: bypass-cache
      description: This HTTP Header variable will bypass cache.
      schema:
        type: string
        enum:
          - 'true'
          - 'false'
        default: 'false'
    smokeParam:
      in: header
      name: smoke
      description: When set to 'true' this HTTP header variable will route the API call to the Integration testing environment. Only applicable in QA.
      schema:
        type: string
  schemas:
    <output_schema_name>:
      type: object
      properties:
        <output_schema_example_string_field>:
          type: string
          description: <description of field contents>
        <output_schema_example_number_field>:
          type: number
          description: <description of field contents> 
    <output_schema_2_name>:
      type: object
      properties:
        <output_schema_2_example_string_field>:
          type: string
          description: <description of field contents>
        <output_schema_2_example_number_field>:
          type: number
          description: <description of field contents> 
