# a
openapi: 3.0.0
info:
  description: |

    This API allows recording of waste data

    The base endpoint URL for this API in production is: `https://marko.aramark.net/v1/REPLACE<base_path>THIS`.

    For testing the API with the "Try" tool on this page or in your app, use either our testing server "qa-marko" or our development server "dev-marko".
  version: 1.0.0-oas3
  title: Security
security:
  - apiKey: []
## a

paths:
  /performance/snapshot/{org_value}:
    get:
      summary: Intra-day performance
      description: |

        Returns snapshot of intra-day performance
# b
        ![This endpoint is in production](/themes/portal/images/statuspngs/statusprod.png)
# c
        ![This endpoint is in qa testing](/themes/portal/images/statuspngs/statusqa.png)
# d
        ![This endpoint is in development](/themes/portal/images/statuspngs/statusdev.png)
## d
      parameters:
# e

        - $ref: '#/components/parameters/pageParam'
        - $ref: '#/components/parameters/sizeParam'
# j
        - $ref: '#/components/parameters/bypassCacheParam'
        - $ref: '#/components/parameters/smokeParam'
# jj
# ee
        - $ref: '#/components/parameters/accountParam'
        - $ref: '#/components/parameters/barcodeParam'
        - $ref: '#/components/parameters/cpgParam'
        - $ref: '#/components/parameters/dateOfBirthParam'
        - $ref: '#/components/parameters/deviceIdParamFalse'
        - $ref: '#/components/parameters/deviceIdParamTrue'
        - $ref: '#/components/parameters/effectiveDateParam'
        - $ref: '#/components/parameters/emailParam'
        - $ref: '#/components/parameters/employeeEmailParam'
        - $ref: '#/components/parameters/employeeIdParam'
        - $ref: '#/components/parameters/employeeIdParamNotRequired'
        - $ref: '#/components/parameters/enabledParam'
        - $ref: '#/components/parameters/endDateParam'
        - $ref: '#/components/parameters/endDateTimeParam'
        - $ref: '#/components/parameters/fieldsParam'
        - $ref: '#/components/parameters/fiscalDayOfWeekParam'
        - $ref: '#/components/parameters/fiscalPeriodParam'
        - $ref: '#/components/parameters/fiscalWeekOfMonthParam'
        - $ref: '#/components/parameters/fiscalYearParam'
        - $ref: '#/components/parameters/formatParam'
        - $ref: '#/components/parameters/groupParam'
        - $ref: '#/components/parameters/hierarchyLevelParam'
        - $ref: '#/components/parameters/hierarchyNameParam'
        - $ref: '#/components/parameters/hierarchyParam'
        - $ref: '#/components/parameters/isAlsrParam'
        - $ref: '#/components/parameters/isHarvestTableParam'
        - $ref: '#/components/parameters/isMm2Param'
        - $ref: '#/components/parameters/isMtoParam'
        - $ref: '#/components/parameters/isPatientParam'
        - $ref: '#/components/parameters/isResidentialParam'
        - $ref: '#/components/parameters/isResultRequiredParam'
        - $ref: '#/components/parameters/isRetailParam'
        - $ref: '#/components/parameters/isSmiParam'
        - $ref: '#/components/parameters/isTempRequiredParam'
        - $ref: '#/components/parameters/isTrueEatsParam'
        - $ref: '#/components/parameters/levelParam'
        - $ref: '#/components/parameters/locationIdParam'
        - $ref: '#/components/parameters/masterSystemIdParam'
        - $ref: '#/components/parameters/mealPeriodIdParam'
        - $ref: '#/components/parameters/orgValueParam'
        - $ref: '#/components/parameters/payPeriodParam'
        - $ref: '#/components/parameters/posParam'
        - $ref: '#/components/parameters/profileIdParamFalse'
        - $ref: '#/components/parameters/profileIdParamTrue'
        - $ref: '#/components/parameters/profitCenterParam'
        - $ref: '#/components/parameters/rankParam'
        - $ref: '#/components/parameters/rawParam'
        - $ref: '#/components/parameters/recipeIdParam'
        - $ref: '#/components/parameters/rollupParam'
        - $ref: '#/components/parameters/searchParam'
        - $ref: '#/components/parameters/segmentCategoryParam'
        - $ref: '#/components/parameters/serviceAreaIdParam'
        - $ref: '#/components/parameters/serviceDateParam'
        - $ref: '#/components/parameters/setIdParamFalse'
        - $ref: '#/components/parameters/setIdParamTrue'
        - $ref: '#/components/parameters/siteIdParam'
        - $ref: '#/components/parameters/sortParam'
        - $ref: '#/components/parameters/sourceSystemParam'
        - $ref: '#/components/parameters/startDateParam'
        - $ref: '#/components/parameters/startDateTimeParam'
        - $ref: '#/components/parameters/statusParam'
        - $ref: '#/components/parameters/subLocationIdParam'
        - $ref: '#/components/parameters/surveyGroupParam'
        - $ref: '#/components/parameters/surveyTypeParam'
        - $ref: '#/components/parameters/updateDateParam'
        - $ref: '#/components/parameters/userIdParam'
        - $ref: '#/components/parameters/userIdParamFalse'
        - $ref: '#/components/parameters/userIdParamTrue'
# f
servers:
  - url: https://qa-marko.aramark.net/v1/alerts
    description: Testing server
  - url: https://dev-marko.aramark.net/v1/alerts
    description: Development server
## f
components:
# h
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: apikey
      description: This HTTP Header variable will verify permissions.
# hh
# m
  parameters:
## m
    userIdParam:
      in: query
      name: user_id
      description: Email address of the manager
      required: true
      schema:
        type: string
    orgValueParam:
      in: path
      name: org_value
      description: provide business organization code in URL to filter data set
      required: true
      schema:
        type: string
    startDateParam:
      in: query
      name: start_date
      description: Calendar date for daily transactions. "mm/dd/yyyy"
      required: false
      schema:
        type: string
    endDateParam:
      in: query
      name: end_date
      description: >-
        Calendar date end date for daily transactions. Will use start_date if
        not provided. "mm/dd/yyyy"
      required: false
      schema:
        type: string
# g
    pageParam:
      in: query
      name: page
      escription: Page number of result set
      required: false
      schema:
        type: number
        default: 1
    sizeParam:
      name: size
      in: query
      description: Number of records to be returned in each page of result set
      schema:
        type: string
        default: 50
# i
    bypassCacheParam:
      in: header
      name: bypass-cache
      description: This HTTP Header variable will bypass cache.
      schema:
        type: string
        enum:
          - 'true'
          - 'false'
        default: false
    smokeParam:
      in: header
      name: smoke
      description: |
        When set to 'true' this HTTP header variable will route the API call to
        the Integration testing environment. Only applicable in QA.
      schema:
        type: string
        default: false
# ii
# gg
# l

        - $ref: '#/components/parameters/serviceDateParam'
        - $ref: '#/components/parameters/locationIdParam'
        - $ref: '#/components/parameters/serviceAreaIdParam'
        - $ref: '#/components/parameters/fieldsParam'
        - $ref: '#/components/parameters/bypassCacheParam'
        - $ref: '#/components/parameters/smokeParam'
 # ll
